[{"model": "admin.logentry", "pk": 69, "fields": {"action_time": "2023-01-11T16:48:05.041Z", "user": 15, "content_type": 14, "object_id": "12", "object_repr": "vlad.jarmola@yandex.ru", "action_flag": 3, "change_message": ""}}, {"model": "admin.logentry", "pk": 70, "fields": {"action_time": "2023-01-11T16:49:33.592Z", "user": 15, "content_type": 4, "object_id": "13", "object_repr": "vlad.jarmola", "action_flag": 3, "change_message": ""}}, {"model": "admin.logentry", "pk": 71, "fields": {"action_time": "2023-01-11T16:51:06.818Z", "user": 15, "content_type": 4, "object_id": "16", "object_repr": "vlad.jarmola", "action_flag": 2, "change_message": "[{\"changed\": {\"fields\": [\"Groups\"]}}]"}}, {"model": "admin.logentry", "pk": 72, "fields": {"action_time": "2023-01-11T16:54:14.554Z", "user": 15, "content_type": 7, "object_id": "5", "object_repr": "vlad.jarmola", "action_flag": 1, "change_message": "[{\"added\": {}}]"}}, {"model": "auth.permission", "pk": 1, "fields": {"name": "Can add log entry", "content_type": 1, "codename": "add_logentry"}}, {"model": "auth.permission", "pk": 2, "fields": {"name": "Can change log entry", "content_type": 1, "codename": "change_logentry"}}, {"model": "auth.permission", "pk": 3, "fields": {"name": "Can delete log entry", "content_type": 1, "codename": "delete_logentry"}}, {"model": "auth.permission", "pk": 4, "fields": {"name": "Can view log entry", "content_type": 1, "codename": "view_logentry"}}, {"model": "auth.permission", "pk": 5, "fields": {"name": "Can add permission", "content_type": 2, "codename": "add_permission"}}, {"model": "auth.permission", "pk": 6, "fields": {"name": "Can change permission", "content_type": 2, "codename": "change_permission"}}, {"model": "auth.permission", "pk": 7, "fields": {"name": "Can delete permission", "content_type": 2, "codename": "delete_permission"}}, {"model": "auth.permission", "pk": 8, "fields": {"name": "Can view permission", "content_type": 2, "codename": "view_permission"}}, {"model": "auth.permission", "pk": 9, "fields": {"name": "Can add group", "content_type": 3, "codename": "add_group"}}, {"model": "auth.permission", "pk": 10, "fields": {"name": "Can change group", "content_type": 3, "codename": "change_group"}}, {"model": "auth.permission", "pk": 11, "fields": {"name": "Can delete group", "content_type": 3, "codename": "delete_group"}}, {"model": "auth.permission", "pk": 12, "fields": {"name": "Can view group", "content_type": 3, "codename": "view_group"}}, {"model": "auth.permission", "pk": 13, "fields": {"name": "Can add user", "content_type": 4, "codename": "add_user"}}, {"model": "auth.permission", "pk": 14, "fields": {"name": "Can change user", "content_type": 4, "codename": "change_user"}}, {"model": "auth.permission", "pk": 15, "fields": {"name": "Can delete user", "content_type": 4, "codename": "delete_user"}}, {"model": "auth.permission", "pk": 16, "fields": {"name": "Can view user", "content_type": 4, "codename": "view_user"}}, {"model": "auth.permission", "pk": 17, "fields": {"name": "Can add content type", "content_type": 5, "codename": "add_contenttype"}}, {"model": "auth.permission", "pk": 18, "fields": {"name": "Can change content type", "content_type": 5, "codename": "change_contenttype"}}, {"model": "auth.permission", "pk": 19, "fields": {"name": "Can delete content type", "content_type": 5, "codename": "delete_contenttype"}}, {"model": "auth.permission", "pk": 20, "fields": {"name": "Can view content type", "content_type": 5, "codename": "view_contenttype"}}, {"model": "auth.permission", "pk": 21, "fields": {"name": "Can add session", "content_type": 6, "codename": "add_session"}}, {"model": "auth.permission", "pk": 22, "fields": {"name": "Can change session", "content_type": 6, "codename": "change_session"}}, {"model": "auth.permission", "pk": 23, "fields": {"name": "Can delete session", "content_type": 6, "codename": "delete_session"}}, {"model": "auth.permission", "pk": 24, "fields": {"name": "Can view session", "content_type": 6, "codename": "view_session"}}, {"model": "auth.permission", "pk": 25, "fields": {"name": "Can add author", "content_type": 7, "codename": "add_author"}}, {"model": "auth.permission", "pk": 26, "fields": {"name": "Can change author", "content_type": 7, "codename": "change_author"}}, {"model": "auth.permission", "pk": 27, "fields": {"name": "Can delete author", "content_type": 7, "codename": "delete_author"}}, {"model": "auth.permission", "pk": 28, "fields": {"name": "Can view author", "content_type": 7, "codename": "view_author"}}, {"model": "auth.permission", "pk": 29, "fields": {"name": "Can add category", "content_type": 8, "codename": "add_category"}}, {"model": "auth.permission", "pk": 30, "fields": {"name": "Can change category", "content_type": 8, "codename": "change_category"}}, {"model": "auth.permission", "pk": 31, "fields": {"name": "Can delete category", "content_type": 8, "codename": "delete_category"}}, {"model": "auth.permission", "pk": 32, "fields": {"name": "Can view category", "content_type": 8, "codename": "view_category"}}, {"model": "auth.permission", "pk": 33, "fields": {"name": "Can add post", "content_type": 9, "codename": "add_post"}}, {"model": "auth.permission", "pk": 34, "fields": {"name": "Can change post", "content_type": 9, "codename": "change_post"}}, {"model": "auth.permission", "pk": 35, "fields": {"name": "Can delete post", "content_type": 9, "codename": "delete_post"}}, {"model": "auth.permission", "pk": 36, "fields": {"name": "Can view post", "content_type": 9, "codename": "view_post"}}, {"model": "auth.permission", "pk": 37, "fields": {"name": "Can add post category", "content_type": 10, "codename": "add_postcategory"}}, {"model": "auth.permission", "pk": 38, "fields": {"name": "Can change post category", "content_type": 10, "codename": "change_postcategory"}}, {"model": "auth.permission", "pk": 39, "fields": {"name": "Can delete post category", "content_type": 10, "codename": "delete_postcategory"}}, {"model": "auth.permission", "pk": 40, "fields": {"name": "Can view post category", "content_type": 10, "codename": "view_postcategory"}}, {"model": "auth.permission", "pk": 41, "fields": {"name": "Can add comment", "content_type": 11, "codename": "add_comment"}}, {"model": "auth.permission", "pk": 42, "fields": {"name": "Can change comment", "content_type": 11, "codename": "change_comment"}}, {"model": "auth.permission", "pk": 43, "fields": {"name": "Can delete comment", "content_type": 11, "codename": "delete_comment"}}, {"model": "auth.permission", "pk": 44, "fields": {"name": "Can view comment", "content_type": 11, "codename": "view_comment"}}, {"model": "auth.permission", "pk": 45, "fields": {"name": "Can add site", "content_type": 12, "codename": "add_site"}}, {"model": "auth.permission", "pk": 46, "fields": {"name": "Can change site", "content_type": 12, "codename": "change_site"}}, {"model": "auth.permission", "pk": 47, "fields": {"name": "Can delete site", "content_type": 12, "codename": "delete_site"}}, {"model": "auth.permission", "pk": 48, "fields": {"name": "Can view site", "content_type": 12, "codename": "view_site"}}, {"model": "auth.permission", "pk": 49, "fields": {"name": "Can add flat page", "content_type": 13, "codename": "add_flatpage"}}, {"model": "auth.permission", "pk": 50, "fields": {"name": "Can change flat page", "content_type": 13, "codename": "change_flatpage"}}, {"model": "auth.permission", "pk": 51, "fields": {"name": "Can delete flat page", "content_type": 13, "codename": "delete_flatpage"}}, {"model": "auth.permission", "pk": 52, "fields": {"name": "Can view flat page", "content_type": 13, "codename": "view_flatpage"}}, {"model": "auth.permission", "pk": 53, "fields": {"name": "Can add email address", "content_type": 14, "codename": "add_emailaddress"}}, {"model": "auth.permission", "pk": 54, "fields": {"name": "Can change email address", "content_type": 14, "codename": "change_emailaddress"}}, {"model": "auth.permission", "pk": 55, "fields": {"name": "Can delete email address", "content_type": 14, "codename": "delete_emailaddress"}}, {"model": "auth.permission", "pk": 56, "fields": {"name": "Can view email address", "content_type": 14, "codename": "view_emailaddress"}}, {"model": "auth.permission", "pk": 57, "fields": {"name": "Can add email confirmation", "content_type": 15, "codename": "add_emailconfirmation"}}, {"model": "auth.permission", "pk": 58, "fields": {"name": "Can change email confirmation", "content_type": 15, "codename": "change_emailconfirmation"}}, {"model": "auth.permission", "pk": 59, "fields": {"name": "Can delete email confirmation", "content_type": 15, "codename": "delete_emailconfirmation"}}, {"model": "auth.permission", "pk": 60, "fields": {"name": "Can view email confirmation", "content_type": 15, "codename": "view_emailconfirmation"}}, {"model": "auth.permission", "pk": 61, "fields": {"name": "Can add social account", "content_type": 16, "codename": "add_socialaccount"}}, {"model": "auth.permission", "pk": 62, "fields": {"name": "Can change social account", "content_type": 16, "codename": "change_socialaccount"}}, {"model": "auth.permission", "pk": 63, "fields": {"name": "Can delete social account", "content_type": 16, "codename": "delete_socialaccount"}}, {"model": "auth.permission", "pk": 64, "fields": {"name": "Can view social account", "content_type": 16, "codename": "view_socialaccount"}}, {"model": "auth.permission", "pk": 65, "fields": {"name": "Can add social application", "content_type": 17, "codename": "add_socialapp"}}, {"model": "auth.permission", "pk": 66, "fields": {"name": "Can change social application", "content_type": 17, "codename": "change_socialapp"}}, {"model": "auth.permission", "pk": 67, "fields": {"name": "Can delete social application", "content_type": 17, "codename": "delete_socialapp"}}, {"model": "auth.permission", "pk": 68, "fields": {"name": "Can view social application", "content_type": 17, "codename": "view_socialapp"}}, {"model": "auth.permission", "pk": 69, "fields": {"name": "Can add social application token", "content_type": 18, "codename": "add_socialtoken"}}, {"model": "auth.permission", "pk": 70, "fields": {"name": "Can change social application token", "content_type": 18, "codename": "change_socialtoken"}}, {"model": "auth.permission", "pk": 71, "fields": {"name": "Can delete social application token", "content_type": 18, "codename": "delete_socialtoken"}}, {"model": "auth.permission", "pk": 72, "fields": {"name": "Can view social application token", "content_type": 18, "codename": "view_socialtoken"}}, {"model": "auth.permission", "pk": 73, "fields": {"name": "Can add category user", "content_type": 19, "codename": "add_categoryuser"}}, {"model": "auth.permission", "pk": 74, "fields": {"name": "Can change category user", "content_type": 19, "codename": "change_categoryuser"}}, {"model": "auth.permission", "pk": 75, "fields": {"name": "Can delete category user", "content_type": 19, "codename": "delete_categoryuser"}}, {"model": "auth.permission", "pk": 76, "fields": {"name": "Can view category user", "content_type": 19, "codename": "view_categoryuser"}}, {"model": "auth.permission", "pk": 77, "fields": {"name": "Can add django job", "content_type": 20, "codename": "add_djangojob"}}, {"model": "auth.permission", "pk": 78, "fields": {"name": "Can change django job", "content_type": 20, "codename": "change_djangojob"}}, {"model": "auth.permission", "pk": 79, "fields": {"name": "Can delete django job", "content_type": 20, "codename": "delete_djangojob"}}, {"model": "auth.permission", "pk": 80, "fields": {"name": "Can view django job", "content_type": 20, "codename": "view_djangojob"}}, {"model": "auth.permission", "pk": 81, "fields": {"name": "Can add django job execution", "content_type": 21, "codename": "add_djangojobexecution"}}, {"model": "auth.permission", "pk": 82, "fields": {"name": "Can change django job execution", "content_type": 21, "codename": "change_djangojobexecution"}}, {"model": "auth.permission", "pk": 83, "fields": {"name": "Can delete django job execution", "content_type": 21, "codename": "delete_djangojobexecution"}}, {"model": "auth.permission", "pk": 84, "fields": {"name": "Can view django job execution", "content_type": 21, "codename": "view_djangojobexecution"}}, {"model": "auth.group", "pk": 1, "fields": {"name": "authors", "permissions": [33, 34, 35, 36]}}, {"model": "auth.user", "pk": 1, "fields": {"password": "pbkdf2_sha256$390000$voNKZ6I6XKIqmfybzLR2m2$yWuX4uTGhbTJzP0/jATCP+z+dj0+s0SJRwjfcpWtjy4=", "last_login": "2023-01-11T08:06:17.737Z", "is_superuser": false, "username": "Ivan", "first_name": "", "last_name": "", "email": "Ivan@ivan.ru", "is_staff": false, "is_active": true, "date_joined": "2022-12-04T16:15:42Z", "groups": [1], "user_permissions": []}}, {"model": "auth.user", "pk": 2, "fields": {"password": "pbkdf2_sha256$390000$SBY7n48MDq0uXr4UetE1MZ$vOqroKsnS3wTcR+oWSoyB84steVbJxCSpeCPIMuypls=", "last_login": "2022-12-27T14:47:25Z", "is_superuser": false, "username": "Lion", "first_name": "", "last_name": "", "email": "lion@lion.ru", "is_staff": false, "is_active": true, "date_joined": "2022-12-04T16:15:50Z", "groups": [1], "user_permissions": []}}, {"model": "auth.user", "pk": 4, "fields": {"password": "!015f8tr0b82EvSa31dFUeEW0ffK7WFeuSoVPqzPm", "last_login": "2022-12-27T17:23:54.116Z", "is_superuser": false, "username": "VladJarmola", "first_name": "Vlad", "last_name": "Jarmola", "email": "VladJarmola@yandex.com", "is_staff": false, "is_active": true, "date_joined": "2022-12-26T16:12:21Z", "groups": [], "user_permissions": []}}, {"model": "auth.user", "pk": 5, "fields": {"password": "pbkdf2_sha256$390000$CCz9LunClKVyQTTHFkKlBp$6HgdtpsySqEYwnN6yPP/i4hPFaQWIcdIL9DgV6RvvLg=", "last_login": "2022-12-27T15:00:50Z", "is_superuser": false, "username": "newauthor", "first_name": "", "last_name": "", "email": "newauthor@new.ru", "is_staff": false, "is_active": true, "date_joined": "2022-12-27T15:00:48Z", "groups": [1], "user_permissions": []}}, {"model": "auth.user", "pk": 6, "fields": {"password": "pbkdf2_sha256$390000$04LfM07tX40Bxd4Ch9pyYc$RkGXkz7trjyDfePPtc7LcQOVn1qyv8gpgV4h9TqDpGs=", "last_login": "2023-01-06T11:42:41.520Z", "is_superuser": false, "username": "test1", "first_name": "", "last_name": "", "email": "test1@test1.ru", "is_staff": false, "is_active": true, "date_joined": "2023-01-06T11:42:40.971Z", "groups": [], "user_permissions": []}}, {"model": "auth.user", "pk": 11, "fields": {"password": "pbkdf2_sha256$390000$5M74JCMvS0zC5FzlLLRwkX$VIHYXEmclCmcP/pne6RdXUyY2GatNHvcF79dmsfrR+0=", "last_login": "2023-01-16T07:12:44.418Z", "is_superuser": false, "username": "taneeenok89", "first_name": "", "last_name": "", "email": "taneeenok89@yandex.ru", "is_staff": false, "is_active": true, "date_joined": "2023-01-10T10:05:14.110Z", "groups": [], "user_permissions": []}}, {"model": "auth.user", "pk": 15, "fields": {"password": "pbkdf2_sha256$390000$D7Z7vyF8i5PVEXomwSWPFE$Mf5JYjy55UUD02/yTSgK9ccDgYc0lzgVut9hMSfoY3A=", "last_login": "2023-01-16T07:13:10.140Z", "is_superuser": true, "username": "admin", "first_name": "", "last_name": "", "email": "", "is_staff": true, "is_active": true, "date_joined": "2023-01-11T16:25:42.110Z", "groups": [], "user_permissions": []}}, {"model": "auth.user", "pk": 16, "fields": {"password": "pbkdf2_sha256$390000$J4VXgHblo7z4FuIxuyiSnB$taIvKjwL+jU3yl6uu1g9h34B7Kw+elZy4X2zhaRhgWg=", "last_login": "2023-01-11T16:51:23.285Z", "is_superuser": false, "username": "vlad.jarmola", "first_name": "", "last_name": "", "email": "vlad.jarmola@yandex.ru", "is_staff": false, "is_active": true, "date_joined": "2023-01-11T16:49:53Z", "groups": [1], "user_permissions": []}}, {"model": "contenttypes.contenttype", "pk": 1, "fields": {"app_label": "admin", "model": "logentry"}}, {"model": "contenttypes.contenttype", "pk": 2, "fields": {"app_label": "auth", "model": "permission"}}, {"model": "contenttypes.contenttype", "pk": 3, "fields": {"app_label": "auth", "model": "group"}}, {"model": "contenttypes.contenttype", "pk": 4, "fields": {"app_label": "auth", "model": "user"}}, {"model": "contenttypes.contenttype", "pk": 5, "fields": {"app_label": "contenttypes", "model": "contenttype"}}, {"model": "contenttypes.contenttype", "pk": 6, "fields": {"app_label": "sessions", "model": "session"}}, {"model": "contenttypes.contenttype", "pk": 7, "fields": {"app_label": "news", "model": "author"}}, {"model": "contenttypes.contenttype", "pk": 8, "fields": {"app_label": "news", "model": "category"}}, {"model": "contenttypes.contenttype", "pk": 9, "fields": {"app_label": "news", "model": "post"}}, {"model": "contenttypes.contenttype", "pk": 10, "fields": {"app_label": "news", "model": "postcategory"}}, {"model": "contenttypes.contenttype", "pk": 11, "fields": {"app_label": "news", "model": "comment"}}, {"model": "contenttypes.contenttype", "pk": 12, "fields": {"app_label": "sites", "model": "site"}}, {"model": "contenttypes.contenttype", "pk": 13, "fields": {"app_label": "flatpages", "model": "flatpage"}}, {"model": "contenttypes.contenttype", "pk": 14, "fields": {"app_label": "account", "model": "emailaddress"}}, {"model": "contenttypes.contenttype", "pk": 15, "fields": {"app_label": "account", "model": "emailconfirmation"}}, {"model": "contenttypes.contenttype", "pk": 16, "fields": {"app_label": "socialaccount", "model": "socialaccount"}}, {"model": "contenttypes.contenttype", "pk": 17, "fields": {"app_label": "socialaccount", "model": "socialapp"}}, {"model": "contenttypes.contenttype", "pk": 18, "fields": {"app_label": "socialaccount", "model": "socialtoken"}}, {"model": "contenttypes.contenttype", "pk": 19, "fields": {"app_label": "news", "model": "categoryuser"}}, {"model": "contenttypes.contenttype", "pk": 20, "fields": {"app_label": "django_apscheduler", "model": "djangojob"}}, {"model": "contenttypes.contenttype", "pk": 21, "fields": {"app_label": "django_apscheduler", "model": "djangojobexecution"}}, {"model": "sessions.session", "pk": "0fknad00v3hqcmbpuau43z3b6xg80tx6", "fields": {"session_data": ".eJxVjEEOgjAQRe_StWlaZjqAS_ecoZnOVEENTSisjHdXEha6_e-9_zKRt3WMW81LnNScDZjT75ZYHnnegd55vhUrZV6XKdldsQetdiian5fD_TsYuY7fWpLSlXNDDSEE77JKK9ihb12bAQkZQ6ME4CmQ9iis3mFw2iUH0gfz_gDVCTcF:1p3uhx:8HaclIDGktIcGLCYTDBG4Wtqzo-E_iyV621sfmzlvOw", "expire_date": "2022-12-24T07:55:41.871Z"}}, {"model": "sessions.session", "pk": "54l62ltjswsj46k6tf81q3wfnfk9lm1j", "fields": {"session_data": ".eJxVjMsOgyAURP-FdWOgPHVXf4RcL5dISjFR6Kbpv1cbNy7nzMz5MEBcWqn-TWuKiYKnF6TMhtJyvjEPrc6-bbT6FNjADLuwCfBJ5Sgg5wN3p677b8566x57olITQk1LGc_XRTXDNu8eFZWYOEUZ4G40oQpWOSmDFTyARWlU0FZxMkIqjJaod9RzrcXknDYg2fcHg1BHWg:1pDl7R:XZVdbPW7dLwIWwpdIuj8L6_DLv96OSUavjXjK8W2D5Q", "expire_date": "2023-01-20T11:42:41.613Z"}}, {"model": "sessions.session", "pk": "94f4x5gs3tk6lk28qr2gm2vpzlzj0ad8", "fields": {"session_data": ".eJxVjEEOwiAQRe_C2hCo4Awu3fcMZBhAqgaS0q6Md7dNutDtf-_9t_C0LsWvPc1-iuIqtBWn3zEQP1PdSXxQvTfJrS7zFOSuyIN2ObaYXrfD_Tso1MtWZxMVDi5opgsjxIiQORsggxAArNUDatDGoFLOsSWFRrFTIW387Kz4fAH8-zcx:1pFeML:R7GeYFOAGg_6iqI0Lzbua-l40mdqtkWV3lGClHjxIkQ", "expire_date": "2023-01-25T16:53:53.943Z"}}, {"model": "sessions.session", "pk": "f1r8wtthwiw6sa82l6awma1uqbftd66n", "fields": {"session_data": ".eJxVjEEOgjAQRe_StWlaZjqAS_ecoZnOVEENTSisjHdXEha6_e-9_zKRt3WMW81LnNScDZjT75ZYHnnegd55vhUrZV6XKdldsQetdiian5fD_TsYuY7fWpLSlXNDDSEE77JKK9ihb12bAQkZQ6ME4CmQ9iis3mFw2iUH0gfz_gDVCTcF:1p2p9w:Xhqf4ZivMTDJKqN7M15jhZq8aMbsa1Hq_0CMx0XBSyw", "expire_date": "2022-12-21T07:48:04.529Z"}}, {"model": "sessions.session", "pk": "kjvapfvngb6nzmgowbvrt5lluh3nato9", "fields": {"session_data": ".eJxVjEEOgjAQRe_StWlaZjqAS_ecoZnOVEENTSisjHdXEha6_e-9_zKRt3WMW81LnNScDZjT75ZYHnnegd55vhUrZV6XKdldsQetdiian5fD_TsYuY7fWpLSlXNDDSEE77JKK9ihb12bAQkZQ6ME4CmQ9iis3mFw2iUH0gfz_gDVCTcF:1pAYks:YDhlPrNELqtsy7on1ezGVB0nLAPB-ZJppnpxAK8-MOA", "expire_date": "2023-01-11T15:54:10.605Z"}}, {"model": "sessions.session", "pk": "lkagmuuo5xwf9dwju7pxnufya7wvqcbb", "fields": {"session_data": ".eJxVjEEOgjAQRe_StWlaZjqAS_ecoZnOVEENTSisjHdXEha6_e-9_zKRt3WMW81LnNScDZjT75ZYHnnegd55vhUrZV6XKdldsQetdiian5fD_TsYuY7fWpLSlXNDDSEE77JKK9ihb12bAQkZQ6ME4CmQ9iis3mFw2iUH0gfz_gDVCTcF:1p2VFH:k0j4lVqGm7bjpLWlw6d4ykaOTDflu3KVAWY8moXLuD4", "expire_date": "2022-12-20T10:32:15.171Z"}}, {"model": "sessions.session", "pk": "oquibj2qs4zoe6h3ziwn6ok2yov7nfrr", "fields": {"session_data": ".eJxVjEEOwiAQRe_C2hCo4Awu3fcMZBhAqgaS0q6Md7dNutDtf-_9t_C0LsWvPc1-iuIqtBWn3zEQP1PdSXxQvTfJrS7zFOSuyIN2ObaYXrfD_Tso1MtWZxMVDi5opgsjxIiQORsggxAArNUDatDGoFLOsSWFRrFTIW387Kz4fAH8-zcx:1pHJg6:zX1ntoCdEmfL7x1lAla2y9REPoNHdcY8NefpV_nyfnU", "expire_date": "2023-01-30T07:13:10.269Z"}}, {"model": "sessions.session", "pk": "tv9x138kn2jke9c0208lwwfifzrk3q3a", "fields": {"session_data": ".eJxVjEEOgjAQRe_StWlaZjqAS_ecoZnOVEENTSisjHdXEha6_e-9_zKRt3WMW81LnNScDZjT75ZYHnnegd55vhUrZV6XKdldsQetdiian5fD_TsYuY7fWpLSlXNDDSEE77JKK9ihb12bAQkZQ6ME4CmQ9iis3mFw2iUH0gfz_gDVCTcF:1p5p1J:E3H19yAzGPgJGQSl3y3TENp5TqTPf8ouSiV6jW4GBpI", "expire_date": "2022-12-29T14:15:33.427Z"}}, {"model": "sessions.session", "pk": "ulne1uzqopu643j19ebuhsyu9v3py88e", "fields": {"session_data": ".eJxVjEEOgjAQRe_StWlaZjqAS_ecoZnOVEENTSisjHdXEha6_e-9_zKRt3WMW81LnNScDZjT75ZYHnnegd55vhUrZV6XKdldsQetdiian5fD_TsYuY7fWpLSlXNDDSEE77JKK9ihb12bAQkZQ6ME4CmQ9iis3mFw2iUH0gfz_gDVCTcF:1p2qAY:M6QmBpJ_Yh9xV0ip5DEOKu_heMFhXpRC8FnCa9tkKrw", "expire_date": "2022-12-21T08:52:46.237Z"}}, {"model": "sites.site", "pk": 1, "fields": {"domain": "127.0.0.1", "name": "example.com"}}, {"model": "news.author", "pk": 1, "fields": {"authorUser": 1, "rating_author": 38}}, {"model": "news.author", "pk": 2, "fields": {"authorUser": 2, "rating_author": 8}}, {"model": "news.author", "pk": 5, "fields": {"authorUser": 16, "rating_author": 0}}, {"model": "news.category", "pk": 1, "fields": {"name_category": "IT", "subscribers": [11, 16]}}, {"model": "news.category", "pk": 3, "fields": {"name_category": "GAME INDUSTRY", "subscribers": []}}, {"model": "news.category", "pk": 4, "fields": {"name_category": "GAMEDEV", "subscribers": []}}, {"model": "news.category", "pk": 5, "fields": {"name_category": "Prog", "subscribers": [6]}}, {"model": "news.post", "pk": 1, "fields": {"author": 1, "choices": "NW", "datatime_of_creation": "2022-12-20T15:45:40.472Z", "heading": "Когда же роботы будут играть в футбол наравне с людьми?", "text": "Отгремел Чемпионат Мира по футболу 2022 («болели» за Аргентину?) и снова всплыл вопрос, которым задаются многие люди с тех пор, когда первый робот смог пнуть «ногой» по мячу: «Когда же роботы будут играть в футбол наравне с людьми?».", "rating": 0}}, {"model": "news.post", "pk": 9, "fields": {"author": 1, "choices": "NW", "datatime_of_creation": "2022-12-20T15:58:01.484Z", "heading": "Создание онлайн сервера для мобильных многопользовательских, realtime 2D игр (жанра RPG и стратегии) с API на PHP ч. 6", "text": "Правительство РФ анонсировало выделение до $50 млрд для выхода РФ в топ-20 стран—разработчиков Игр к 2030 году. Возможно в скором времени разрабатываемый мной сервис наконец увидит свет", "rating": 0}}, {"model": "news.post", "pk": 10, "fields": {"author": 1, "choices": "NW", "datatime_of_creation": "2022-12-20T15:59:32.917Z", "heading": "Продолжение тестирования i.MX RT на плате MIMXRT1170-EVK", "text": "В прошлой статье было начато тестирование чипов семейства i.MX RT. Здесь продолжаем тестировать.", "rating": 0}}, {"model": "news.post", "pk": 11, "fields": {"author": 1, "choices": "NW", "datatime_of_creation": "2022-12-20T16:00:06.772Z", "heading": "TOTP-аутентификатор на самодельном компьютере", "text": "Здравствуйте, господа программисты и не только. Снова наш веселый Отдел Перспективных Разработок выходит на связь с новой заметкой, посвященной очередной бесполезной, но, интересной для весьма узких кругов теме.", "rating": 0}}, {"model": "news.post", "pk": 12, "fields": {"author": 1, "choices": "NW", "datatime_of_creation": "2022-12-20T16:00:39.122Z", "heading": "Для этого не нужна ARIA", "text": "В веб-разработке написание семантического HTML важно для доступности, а также дает некоторые приятные побочные эффекты, такие как поддержка режима «чтения» в браузере, SEO, graceful degradation и возможность экспорта.", "rating": 0}}, {"model": "news.post", "pk": 13, "fields": {"author": 1, "choices": "NW", "datatime_of_creation": "2022-12-20T16:01:05.623Z", "heading": "Взгляд на современные паттерны интеграции: Enterprise Design Thinking и Event Driven Architecture", "text": "Привет Хабр! Меня зовут Рустем, IBM Senior DevOps Engineer & Integration Architect.  Сегодня я хотел бы взглянуть на современные паттерны интеграции: Enterprise Design Thinking и Event Driven Architecture.  Читать далее", "rating": 0}}, {"model": "news.post", "pk": 14, "fields": {"author": 1, "choices": "NW", "datatime_of_creation": "2022-12-20T16:01:30.718Z", "heading": "38 лучших CI/CD-инструментов в 2022 году", "text": "Непрерывная интеграция (CI) и непрерывная доставка (CD) или CI/CD стали неотъемлемой частью подхода к разработке программного обеспечения и тестирования DevOps. Этот подход дает разработчикам возможность непрерывного развертывания кода. Кроме того, ошибки выявляются на ранней стадии, что позволяет избежать проблем с интеграцией из-за частой фиксации исходного кода.", "rating": 0}}, {"model": "news.post", "pk": 15, "fields": {"author": 1, "choices": "NW", "datatime_of_creation": "2022-12-20T16:02:11.580Z", "heading": "Алгоритмы диапазонов C++20 — 7 немодифицирующих операций", "text": "Библиотека Ranges для C++20 предлагает альтернативы для большинства алгоритмов. На этот раз я хочу показать вам десять немодифицирующих операций. Мы сравним их со «старой» стандартной версией и увидим их преимущества и ограничения.", "rating": 0}}, {"model": "news.post", "pk": 16, "fields": {"author": 1, "choices": "NW", "datatime_of_creation": "2022-12-20T16:02:47.051Z", "heading": "SimpleX – первый мессенджер без идентификаторов пользователей", "text": "Сегодня рассказываем про анонимный мессенджер SimpleX, который написан на Haskell и позволяет, в том числе, использовать сеть Tor для общения.    ​​SimpleX – не только один из немногих мессенджеров, который не", "rating": 0}}, {"model": "news.post", "pk": 17, "fields": {"author": 1, "choices": "NW", "datatime_of_creation": "2022-12-20T16:03:16.361Z", "heading": "10 Онлайн мини-игр прошлой недели, чтобы развлечься #4", "text": "В этом выпуске: защита башен от привидений и рыцарей, шахматные бои, поиск предметов с милыми котиками, платформеры и разнообразные по сложности головоломки. Все игры доступны в онлайне и это подборка с itch.io.", "rating": 0}}, {"model": "news.post", "pk": 18, "fields": {"author": 1, "choices": "NW", "datatime_of_creation": "2022-12-20T16:03:41.216Z", "heading": "Как дизайнить приложения, если ты не дизайнер? Пошаговая инструкция", "text": "Вы когда-нибудь хотели создать приложение, но не знали, с чего начать? Независимо от того, являетесь ли вы предпринимателем, разработчиком, продакт менеджером, или просто любопытным человеком, эта статья покажет вам, как создать дизайн мобильного приложения, даже если у вас нет опыта в дизайне.", "rating": 0}}, {"model": "news.post", "pk": 19, "fields": {"author": 1, "choices": "NW", "datatime_of_creation": "2022-12-20T16:04:44.471Z", "heading": "Борьба с клеветой в интернете: опыт Канады", "text": "Информация, не соответствующая действительности, оценивается по-разному, затрагивает интересы и права разных лиц, включая государство. В зависимости от вредности своего содержания, информация может быть признана клеветой, порочащим материалом или поклепом, в соответствии с законодательством Канады.", "rating": 0}}, {"model": "news.post", "pk": 20, "fields": {"author": 2, "choices": "PR", "datatime_of_creation": "2022-12-20T16:05:23.835Z", "heading": "Исследование: детям не стоит давать гаджеты, чтобы они успокаивались", "text": "Попытки отвлечь детей от истерики экраном планшета или телефона приводят к тому, что ребёнок лишь захочет проводить больше времени с гаджетом, но никак не помогают справиться с проблемой контроля эмоций. Об этом говорится в результатах исследования, опубликованном в журнале JAMA Pediatrics.", "rating": 0}}, {"model": "news.post", "pk": 21, "fields": {"author": 2, "choices": "PR", "datatime_of_creation": "2022-12-20T16:05:58.171Z", "heading": "Физик создал математическую модель путешествий во времени без парадоксов", "text": "Хотя пока ещё никому не удавалось отправиться в прошлое, мы можем рассуждать о возможности такого перемещения и о тех проблемах, которые оно может принести. В частности, одна из проблем с такими путешествиями сформулирована в т.н. «парадоксе дедушки». Если путешественник в прошлое убьёт своего дедушку в молодости (или как-то иначе помешает ему оставить потомство), тогда этот путешественник не должен будет родиться – но тогда кто отправился назад в прошлое и убил дедушку?", "rating": 0}}, {"model": "news.post", "pk": 22, "fields": {"author": 2, "choices": "PR", "datatime_of_creation": "2022-12-20T16:06:34.020Z", "heading": "Предложен универсальный метод повышения стабильности солнечных батарей", "text": "Сотрудники лаборатории новых материалов для солнечной энергетики ФНМ МГУ проводят тестирование долговременной стабильности солнечных элементов. Источник: Алексей Тарасов/МГУ", "rating": 0}}, {"model": "news.post", "pk": 23, "fields": {"author": 2, "choices": "PR", "datatime_of_creation": "2022-12-20T16:07:01.027Z", "heading": "Amazon запустила Prime Gaming в Индии", "text": "Американская компания Amazon запустила игровой сервис Prime Gaming в Индии. Он позволяет получить доступ к ряду видеоигр. Компания начала тестировать сервис на рынках Южной Азии в начале декабря. Индийцы смогут воспользоваться Prime Gaming через несколько недель.", "rating": 0}}, {"model": "news.post", "pk": 24, "fields": {"author": 2, "choices": "PR", "datatime_of_creation": "2022-12-20T16:07:35.130Z", "heading": "НАСА сообщило о низком уровне заряда батарей InSight и опубликовало прощание зонда", "text": "НАСА сообщило об очень низком уровне заряда батарей InSight. Агентство также опубликовало в Twitter последнее фото и трогательное прощание от имени марсианского зонда.", "rating": 0}}, {"model": "news.post", "pk": 25, "fields": {"author": 2, "choices": "PR", "datatime_of_creation": "2022-12-20T16:07:59.056Z", "heading": "В Роскосмосе решают — вернуть международный экипаж с МКС на Землю на резервном корабле или на поврежденном «Союзе МС-22»", "text": "В Роскосмосе до конца декабря решат, как вернуть международный экипаж с МКС на Землю — на резервном корабле «Союз МС-23» или после понимания, что возможно возвращение на «Союзе МС-22» после восстановления работоспособности повреждённой системы.", "rating": 0}}, {"model": "news.post", "pk": 26, "fields": {"author": 2, "choices": "PR", "datatime_of_creation": "2022-12-20T16:08:26.834Z", "heading": "Пока Маск не видит достойных преемников на должность гендира Twitter, журналисты составляют свои списки кандидатов", "text": "После того, как в Twitter закончился опрос, должен ли Илон Маск уходить с поста гендиректора соцсети, медиасообщество пытается представить дальнейшее развитие событий. CNN уже составила список наиболее вероятных претендентов на место Маска, один из добровольцев быстро организовал собственный опрос, а Маск озвучил свою позицию: нет никого, кто и хотел бы, и мог управлять Twitter.", "rating": 0}}, {"model": "news.post", "pk": 27, "fields": {"author": 2, "choices": "PR", "datatime_of_creation": "2022-12-20T16:08:56.038Z", "heading": "Минцифры планирует запустить российский аналог «Википедии» в начале 2023 года", "text": "Запуск портала «Знания», российского аналога «Википедии», намечен на начало 2023 года. Об этом в ходе правительственного часа в Госдуме сообщил глава Минцифры Максут Шадаев.  Читать далее", "rating": 0}}, {"model": "news.post", "pk": 28, "fields": {"author": 2, "choices": "PR", "datatime_of_creation": "2022-12-20T16:09:28.477Z", "heading": "Практикум по nanoCAD BIM ОПС впервые прошел в Красноярске", "text": "«Нанософт разработка» и ее фокус-партнер по направлению «Инженерия», компания «ИнфоИндастри», впервые провели в Красноярске практикум по программному продукту nanoCAD BIM ОПС. Функционал ПО был протестирован на примере реального объекта", "rating": 0}}, {"model": "news.post", "pk": 29, "fields": {"author": 2, "choices": "PR", "datatime_of_creation": "2022-12-20T16:09:54.578Z", "heading": "«Яндекс.Маркет» приступил к продажам телевизоров под собственной маркой Tuvio", "text": "В маркетплейсе «Яндекс.Маркет» запустили продажи электроники и бытовой техники под собственным брендом «Яндекса» Tuvio, рассказали Хабру в пресс-службе компании. Потребители могут оформить заказ на телевизоры Tuvio с 43-дюймовым экраном, до конца года в продажу поступят 32-дюймовые ТВ. В ближайшее время на маркетплейсе начнут реализовывать холодильники, стиральные машины, микроволновые печи и другую домашнюю технику и электронику новых марок «Яндекса».", "rating": 0}}, {"model": "news.post", "pk": 30, "fields": {"author": 2, "choices": "PR", "datatime_of_creation": "2022-12-20T16:10:26.089Z", "heading": "РЖД и «Транстелеком» объединили бесшовным Wi-Fi поезда «Сапсан» и вокзалы Москвы, Санкт-Петербурга и Твери", "text": "ОАО «РЖД» вместе с федеральным оператором связи АО «Компания Транстелеком» организовали бесшовный Wi-Fi на нескольких вокзалах и в поездах «Сапсан». Единая сеть охватывает Московский вокзал в Санкт-Петербурге, Ленинградский – в Москве, вокзалы Тверь и Бологое.", "rating": 0}}, {"model": "news.post", "pk": 31, "fields": {"author": 2, "choices": "PR", "datatime_of_creation": "2022-12-20T16:12:21.953Z", "heading": "Минцифры: около 100 тыс. IT-специалистов покинули РФ в этом году, 80% из них продолжают работать на российские компании", "text": "20 декабря 2022 года глава Минцифры Максут Шадаев сообщил на заседании в Госдуме, что около 100 тыс. российских IT-специалистов покинули страну в этом году.", "rating": 0}}, {"model": "news.post", "pk": 32, "fields": {"author": 2, "choices": "NW", "datatime_of_creation": "2022-12-21T14:45:52.412Z", "heading": "Спрос на продвижение в Telegram значительно вырос на фоне ухода из России иностранных платформ", "text": "Рекламодатели увеличили траты на продвижение в Telegram-каналах — число нативных постов с упоминаниями внешних сайтов увеличилось на 129%, сообщает «Коммерсантъ» со ссылкой на аналитиков SocialJet и TGStat. Общий же рост вложений, по разным оценкам, составляет до 200%", "rating": 0}}, {"model": "news.post", "pk": 33, "fields": {"author": 1, "choices": "NW", "datatime_of_creation": "2022-12-21T14:46:17.156Z", "heading": "«Аэродиск» и AUXO заключили партнёрское соглашение", "text": "IT-компания AUXO и российский разработчик и производитель инновационных решений в области хранения данных и виртуализации «Аэродиск» заключили партнёрское соглашение, рассказали Хабру в пресс-службе AUXO. Партнёрство позволит объединить компетенции «Аэродиск» в области инновационных разработок и опыт AUXO в решении широкого круга IT-задач в госсекторе, промышленном производстве, здравоохранении, телекоме, финансовой сфере и других отраслях. На данном этапе предполагается реализация проектного подхода, где специалисты AUXO будут оценивать возможности использования продуктов вендора по итогам аудита потребностей клиентов.", "rating": 0}}, {"model": "news.post", "pk": 34, "fields": {"author": 1, "choices": "PR", "datatime_of_creation": "2022-12-21T14:48:17.242Z", "heading": "Нельзя просто взять и обезличить данные — опыт команды разработки «Сферы»", "text": "Бизнесу нельзя использовать данные клиентов as is для тестов. Отдел разработки не может просто взять персональные данные (ПДн) и проверить на них новую фичу, обучить Machine Learning-модель. Этот момент регулируют законы и отраслевые стандарты. Чтобы с данными можно было работать, их необходимо обезличить. В крупных компаниях сотни таблиц переплетены идентификаторами, формулами, процедурами. И здесь речь идет уже о формировании обезличенных интеграционных полигонов (комплексов БД). Максим Никитин, тимлид группы разработки, поделится опытом команды разработки платформы производства ПО «Сфера».", "rating": 0}}, {"model": "news.post", "pk": 36, "fields": {"author": 1, "choices": "NW", "datatime_of_creation": "2023-01-09T07:47:44.470Z", "heading": "Изучение TypeScript", "text": "Все привет! Меня зовут Лихопой Кирилл и я - fullstack-разработчик. В заключительной части руководства мы рассмотрим строгий режим и сужение типов в TypeScript. Эти техники позволяют точнее определять типы в коде, чтобы улучшить качество вашего кода и уменьшить количество багов.  Другие части: Часть 1 - Введение и примитивы Часть 2 - Ссылочные типы данных Часть 3 - Классы и интерфейсы Часть 4 - Литералы и дженерики", "rating": 0}}, {"model": "news.post", "pk": 40, "fields": {"author": 2, "choices": "NW", "datatime_of_creation": "2023-01-09T07:59:41.232Z", "heading": "Как я написал книгу по Java", "text": "Буквально недавно книга окончательно вышла, и её можно купить на сайте издательства, а авторские экземпляры получены и хранятся у меня.  Сразу должен сказать, что книга точно не для начинающих. В некоторых главах рассматриваются довольно углублённые технические вопросы, которые новичка скорее запутают, чем облегчат ему освоение программирования. Особое внимание уделено изменениям, которые происходили от версии к версии, а также некоторым внутренним особенностям языка. Из-за длительного периода развития в Java накопилось порядочно «костылей», благодаря которым старый код остаётся работоспособным, но которые могут запутать программиста. В книге описываются основные моменты, которые нужно помнить при разработке, для того чтобы ваш код работал именно так, как вы бы хотели.  Я не особо популярная личность, поэтому не ожидаю какого-либо ажиотажа, но буду стараться, чтобы книгу купило как можно большее количество людей.", "rating": 0}}, {"model": "news.post", "pk": 42, "fields": {"author": 1, "choices": "NW", "datatime_of_creation": "2023-01-10T10:41:01.812Z", "heading": "Apple двукратно нарастила экспорт iPhone из Индии", "text": "В период с апреля по декабрь 2022 года американская компания Apple экспортировала из Индии iPhone на более чем $2,5 млрд, демонстрирует отчёт Bloomberg. Эта сумма почти вдвое превышает показатели экспорта из страны за 2021 год.", "rating": 0}}, {"model": "news.post", "pk": 48, "fields": {"author": 1, "choices": "NW", "datatime_of_creation": "2023-01-10T15:35:39.721Z", "heading": "Vinpower представила зарядную станцию iXcharger GaN 65 Вт с 1TБ памяти для бэкапов", "text": "Vinpower анонсировала зарядную станцию iXcharger со встроенным хранилищем объёмом в 1 ТБ. Во время зарядки устройство делает резервную копию фотографий и видео с iPhone и iPad. Также его можно использовать как обычное внешнее хранилище.", "rating": 0}}, {"model": "news.post", "pk": 73, "fields": {"author": 1, "choices": "NW", "datatime_of_creation": "2023-01-10T16:45:57.110Z", "heading": "Модели управления инфраструктурой", "text": "Управление инфраструктурой даже средней организации является непростой задачей. Большое количество серверов требует постоянного внимания. Установка обновлений и развертывание новых систем все это трудоемкие задачи. Поговорим о том, каким способами можно автоматизировать выполнение данных задач.", "rating": 0}}, {"model": "news.post", "pk": 78, "fields": {"author": 1, "choices": "NW", "datatime_of_creation": "2023-01-11T09:02:59.079Z", "heading": "test", "text": "test 000000000000000000000000000000000000000000000", "rating": 0}}, {"model": "news.post", "pk": 79, "fields": {"author": 2, "choices": "NW", "datatime_of_creation": "2023-01-11T10:39:07.200Z", "heading": "Compliance-дайджест: что изменилось в ИБ-законодательстве в декабре 2022", "text": "На связи Катя из центра «Solar Интеграция» с подборкой новостей из мира комплаенса ИБ за минувший декабрь. Как изменились формы уведомлений в области обработки персональных данных, которые необходимо направлять в Роскомнадзор? Какие новшества появились в области защиты критической информационной инфраструктуры? Что должны уметь ИБ-специалисты в кредитно-финансовой сфере, согласно новому профстандарту? Какие нормативные правовые акты планирует разработать ФСТЭК России в 2023 году? Об этом и не только расскажу в новом выпуске дайджеста.", "rating": 0}}, {"model": "news.post", "pk": 80, "fields": {"author": 2, "choices": "NW", "datatime_of_creation": "2023-01-11T10:41:57.575Z", "heading": "Двухфакторная аутентификация пользователей в Carbonio", "text": "Помимо парольной политики безопасности, о которой мы писали в нашей прошлой статье, и которая может создавать массу неудобств для пользователей и, соответственно, для системных администраторов, к которым эти пользователи обращаются, еще одним способом повысить защищенность учетных записей является двухфакторная аутентификация пользователей. Этот механизм добавляет к необходимости ввода пароля учетной записи необходимость для пользователя вводить временный одноразовый пароль, который случайно генерируется на его устройстве. Такая мера защиты делает практически бесполезным любой брутфорс, а при грамотной настройке может быть совершенно незаметна для пользователей.  Отметим, что 2FA от Carbonio совместима с любыми решениями для генерации одноразовых паролей, в том числе отечественных, а благодаря использованию двухфакторной аутентификации Carbonio достигает 6-го уровня по 8-ми уровневой модели защищенности аутентификации CASMMv5.", "rating": 0}}, {"model": "news.post", "pk": 81, "fields": {"author": 2, "choices": "NW", "datatime_of_creation": "2023-01-11T10:42:51.076Z", "heading": "книг по компьютерному «железу» для новичков и профи", "text": "Привет, Хабр! Мы продолжаем публиковать подборки профессиональной литературы разных направлений для представителей IT-отрасли. Эта статья посвящена компьютерному «железу». В подборке — как относительно базовые книги, так и более продвинутые. Найти что-то полезное для себя в них сможет как человек, который не очень хорошо разбирается в аппаратном обеспечении, так и профессионал, решивший углубить знания или заполнить пробелы. Всё самое интересное — ниже.", "rating": 0}}, {"model": "news.post", "pk": 84, "fields": {"author": 1, "choices": "NW", "datatime_of_creation": "2023-01-11T16:52:11.943Z", "heading": "sfvsdvsv", "text": "fdbdfbdfbdfbdfbdfbdsfbdsbdfb", "rating": 0}}, {"model": "news.post", "pk": 90, "fields": {"author": 1, "choices": "NW", "datatime_of_creation": "2023-01-16T07:07:37.161Z", "heading": "Популяризация JSON-RPC (часть 2)", "text": "Продолжим строить подобие JSON-RPC сервера, начатого в части 1 и анализировать его плюсы и минусы. В прошлой статье был описан механизм отделения бизнес логики бэкенда от транспортного протокола (HTTP) через шаблон проектирования \"Front Controller\", который исполняет в нашем случае JsonRpcController.  Бэкенд API до передачи запроса в код, отвечающий за бизнес логику, обычно предоставляет частичный функционал API шлюза (API gateway) - он может делать аутентификацию, авторизацию, роутинг, валидацию данных, логгирование, кэширование, обеспечивать меры безопасности и другое.", "rating": 0}}, {"model": "news.post", "pk": 91, "fields": {"author": 2, "choices": "NW", "datatime_of_creation": "2023-01-16T07:13:59.527Z", "heading": "Проверка", "text": "Какойто текст 00000000000000000", "rating": 0}}, {"model": "news.post", "pk": 92, "fields": {"author": 1, "choices": "NW", "datatime_of_creation": "2023-01-16T07:18:02.843Z", "heading": "Проверка2", "text": "Проверка дополнительных параметров выполнения", "rating": 0}}, {"model": "news.post", "pk": 93, "fields": {"author": 1, "choices": "NW", "datatime_of_creation": "2023-01-16T07:23:47.748Z", "heading": "Проверка3", "text": "Проверка без expires .000000000", "rating": 0}}, {"model": "news.post", "pk": 94, "fields": {"author": 1, "choices": "NW", "datatime_of_creation": "2023-01-18T04:14:48.502Z", "heading": "Проверка кэширования3", "text": "какой то текст 444444444444444444", "rating": 0}}, {"model": "news.postcategory", "pk": 10, "fields": {"post": 1, "category": 1}}, {"model": "news.postcategory", "pk": 14, "fields": {"post": 12, "category": 1}}, {"model": "news.postcategory", "pk": 17, "fields": {"post": 15, "category": 1}}, {"model": "news.postcategory", "pk": 18, "fields": {"post": 16, "category": 1}}, {"model": "news.postcategory", "pk": 19, "fields": {"post": 17, "category": 1}}, {"model": "news.postcategory", "pk": 20, "fields": {"post": 18, "category": 1}}, {"model": "news.postcategory", "pk": 21, "fields": {"post": 19, "category": 1}}, {"model": "news.postcategory", "pk": 22, "fields": {"post": 20, "category": 1}}, {"model": "news.postcategory", "pk": 23, "fields": {"post": 21, "category": 1}}, {"model": "news.postcategory", "pk": 24, "fields": {"post": 22, "category": 1}}, {"model": "news.postcategory", "pk": 25, "fields": {"post": 23, "category": 1}}, {"model": "news.postcategory", "pk": 26, "fields": {"post": 24, "category": 1}}, {"model": "news.postcategory", "pk": 27, "fields": {"post": 25, "category": 1}}, {"model": "news.postcategory", "pk": 28, "fields": {"post": 26, "category": 1}}, {"model": "news.postcategory", "pk": 29, "fields": {"post": 27, "category": 1}}, {"model": "news.postcategory", "pk": 30, "fields": {"post": 28, "category": 1}}, {"model": "news.postcategory", "pk": 31, "fields": {"post": 29, "category": 1}}, {"model": "news.postcategory", "pk": 32, "fields": {"post": 30, "category": 1}}, {"model": "news.postcategory", "pk": 34, "fields": {"post": 32, "category": 1}}, {"model": "news.postcategory", "pk": 37, "fields": {"post": 34, "category": 1}}, {"model": "news.postcategory", "pk": 38, "fields": {"post": 33, "category": 5}}, {"model": "news.postcategory", "pk": 39, "fields": {"post": 31, "category": 5}}, {"model": "news.postcategory", "pk": 40, "fields": {"post": 14, "category": 5}}, {"model": "news.postcategory", "pk": 41, "fields": {"post": 13, "category": 5}}, {"model": "news.postcategory", "pk": 42, "fields": {"post": 11, "category": 5}}, {"model": "news.postcategory", "pk": 43, "fields": {"post": 10, "category": 5}}, {"model": "news.postcategory", "pk": 44, "fields": {"post": 9, "category": 5}}, {"model": "news.postcategory", "pk": 45, "fields": {"post": 36, "category": 1}}, {"model": "news.postcategory", "pk": 46, "fields": {"post": 40, "category": 1}}, {"model": "news.postcategory", "pk": 48, "fields": {"post": 42, "category": 1}}, {"model": "news.postcategory", "pk": 49, "fields": {"post": 48, "category": 1}}, {"model": "news.postcategory", "pk": 66, "fields": {"post": 73, "category": 1}}, {"model": "news.postcategory", "pk": 71, "fields": {"post": 78, "category": 1}}, {"model": "news.postcategory", "pk": 72, "fields": {"post": 79, "category": 5}}, {"model": "news.postcategory", "pk": 73, "fields": {"post": 80, "category": 1}}, {"model": "news.postcategory", "pk": 74, "fields": {"post": 81, "category": 5}}, {"model": "news.postcategory", "pk": 77, "fields": {"post": 84, "category": 1}}, {"model": "news.postcategory", "pk": 78, "fields": {"post": 90, "category": 1}}, {"model": "news.postcategory", "pk": 79, "fields": {"post": 91, "category": 1}}, {"model": "news.postcategory", "pk": 80, "fields": {"post": 92, "category": 1}}, {"model": "news.postcategory", "pk": 81, "fields": {"post": 93, "category": 1}}, {"model": "news.postcategory", "pk": 82, "fields": {"post": 94, "category": 3}}, {"model": "account.emailaddress", "pk": 1, "fields": {"user": 4, "email": "VladJarmola@yandex.com", "verified": true, "primary": true}}, {"model": "account.emailaddress", "pk": 2, "fields": {"user": 5, "email": "newauthor@new.ru", "verified": false, "primary": true}}, {"model": "account.emailaddress", "pk": 3, "fields": {"user": 6, "email": "test1@test1.ru", "verified": false, "primary": true}}, {"model": "account.emailaddress", "pk": 8, "fields": {"user": 11, "email": "taneeenok89@yandex.ru", "verified": true, "primary": true}}, {"model": "account.emailaddress", "pk": 10, "fields": {"user": 1, "email": "Ivan@ivan.ru", "verified": false, "primary": false}}, {"model": "account.emailaddress", "pk": 13, "fields": {"user": 16, "email": "vlad.jarmola@yandex.ru", "verified": true, "primary": true}}, {"model": "socialaccount.socialapp", "pk": 1, "fields": {"provider": "yandex", "name": "Yandex", "client_id": "8b716fdd26d34213ade2fde912aa39a6", "secret": "1577c899cb484ecfba0f850cd6396dae", "key": "", "sites": [1]}}, {"model": "socialaccount.socialaccount", "pk": 1, "fields": {"user": 4, "provider": "yandex", "uid": "1732620311", "last_login": "2022-12-27T17:23:53.756Z", "date_joined": "2022-12-26T16:12:21.237Z", "extra_data": "{\"id\": \"1732620311\", \"login\": \"VladJarmola\", \"client_id\": \"8b716fdd26d34213ade2fde912aa39a6\", \"display_name\": \"VladJarmola\", \"real_name\": \"Vlad Jarmola\", \"first_name\": \"Vlad\", \"last_name\": \"Jarmola\", \"sex\": null, \"default_email\": \"VladJarmola@yandex.com\", \"emails\": [\"VladJarmola@yandex.com\"], \"psuid\": \"1.AAjyuQ.vXz7fa73gEsORaXuSw98Gw.w8ii87H2QpKrYdudj5Y0lQ\"}"}}, {"model": "django_apscheduler.djangojob", "pk": "delete_old_job_executions", "fields": {"next_run_time": "2023-01-15T18:00:00Z", "job_state": "gAWVkQQAAAAAAAB9lCiMB3ZlcnNpb26USwGMAmlklIwZZGVsZXRlX29sZF9qb2JfZXhlY3V0aW9uc5SMBGZ1bmOUjEFuZXdzLm1hbmFnZW1lbnQuY29tbWFuZHMucnVuYXBzY2hlZHVsZXI6ZGVsZXRlX29sZF9qb2JfZXhlY3V0aW9uc5SMB3RyaWdnZXKUjBlhcHNjaGVkdWxlci50cmlnZ2Vycy5jcm9ulIwLQ3JvblRyaWdnZXKUk5QpgZR9lChoAUsCjAh0aW1lem9uZZSMG3B5dHpfZGVwcmVjYXRpb25fc2hpbS5faW1wbJSMCXdyYXBfem9uZZSTlIwIYnVpbHRpbnOUjAdnZXRhdHRylJOUjBJiYWNrcG9ydHMuem9uZWluZm+UjAhab25lSW5mb5STlIwJX3VucGlja2xllIaUUpSMCUFzaWEvT21za5RLAYaUUpRoGYaUUpSMCnN0YXJ0X2RhdGWUTowIZW5kX2RhdGWUTowGZmllbGRzlF2UKIwgYXBzY2hlZHVsZXIudHJpZ2dlcnMuY3Jvbi5maWVsZHOUjAlCYXNlRmllbGSUk5QpgZR9lCiMBG5hbWWUjAR5ZWFylIwKaXNfZGVmYXVsdJSIjAtleHByZXNzaW9uc5RdlIwlYXBzY2hlZHVsZXIudHJpZ2dlcnMuY3Jvbi5leHByZXNzaW9uc5SMDUFsbEV4cHJlc3Npb26Uk5QpgZR9lIwEc3RlcJROc2JhdWJoIowKTW9udGhGaWVsZJSTlCmBlH2UKGgnjAVtb250aJRoKYhoKl2UaC4pgZR9lGgxTnNiYXViaCKMD0RheU9mTW9udGhGaWVsZJSTlCmBlH2UKGgnjANkYXmUaCmIaCpdlGguKYGUfZRoMU5zYmF1YmgijAlXZWVrRmllbGSUk5QpgZR9lChoJ4wEd2Vla5RoKYhoKl2UaC4pgZR9lGgxTnNiYXViaCKMDkRheU9mV2Vla0ZpZWxklJOUKYGUfZQoaCeMC2RheV9vZl93ZWVrlGgpiWgqXZRoLIwWV2Vla2RheVJhbmdlRXhwcmVzc2lvbpSTlCmBlH2UKGgxTowFZmlyc3SUSwCMBGxhc3SUSwB1YmF1YmgkKYGUfZQoaCeMBGhvdXKUaCmJaCpdlGgsjA9SYW5nZUV4cHJlc3Npb26Uk5QpgZR9lChoMU5oVEsAaFVLAHViYXViaCQpgZR9lChoJ4wGbWludXRllGgpiWgqXZRoWymBlH2UKGgxTmhUSwBoVUsAdWJhdWJoJCmBlH2UKGgnjAZzZWNvbmSUaCmIaCpdlGhbKYGUfZQoaDFOaFRLAGhVSwB1YmF1YmWMBmppdHRlcpROdWKMCGV4ZWN1dG9ylIwHZGVmYXVsdJSMBGFyZ3OUKYwGa3dhcmdzlH2UaCdoA4wSbWlzZmlyZV9ncmFjZV90aW1llEsBjAhjb2FsZXNjZZSIjA1tYXhfaW5zdGFuY2VzlEsBjA1uZXh0X3J1bl90aW1llIwIZGF0ZXRpbWWUjAhkYXRldGltZZSTlEMKB+cBEAAAAAAAAJRoHYaUUpR1Lg=="}}, {"model": "django_apscheduler.djangojob", "pk": "my_job", "fields": {"next_run_time": "2023-01-17T07:46:00Z", "job_state": "gAWVawQAAAAAAAB9lCiMB3ZlcnNpb26USwGMAmlklIwGbXlfam9ilIwEZnVuY5SMLm5ld3MubWFuYWdlbWVudC5jb21tYW5kcy5ydW5hcHNjaGVkdWxlcjpteV9qb2KUjAd0cmlnZ2VylIwZYXBzY2hlZHVsZXIudHJpZ2dlcnMuY3JvbpSMC0Nyb25UcmlnZ2VylJOUKYGUfZQoaAFLAowIdGltZXpvbmWUjBtweXR6X2RlcHJlY2F0aW9uX3NoaW0uX2ltcGyUjAl3cmFwX3pvbmWUk5SMCGJ1aWx0aW5zlIwHZ2V0YXR0cpSTlIwSYmFja3BvcnRzLnpvbmVpbmZvlIwIWm9uZUluZm+Uk5SMCV91bnBpY2tsZZSGlFKUjAlBc2lhL09tc2uUSwGGlFKUaBmGlFKUjApzdGFydF9kYXRllE6MCGVuZF9kYXRllE6MBmZpZWxkc5RdlCiMIGFwc2NoZWR1bGVyLnRyaWdnZXJzLmNyb24uZmllbGRzlIwJQmFzZUZpZWxklJOUKYGUfZQojARuYW1llIwEeWVhcpSMCmlzX2RlZmF1bHSUiIwLZXhwcmVzc2lvbnOUXZSMJWFwc2NoZWR1bGVyLnRyaWdnZXJzLmNyb24uZXhwcmVzc2lvbnOUjA1BbGxFeHByZXNzaW9ulJOUKYGUfZSMBHN0ZXCUTnNiYXViaCKMCk1vbnRoRmllbGSUk5QpgZR9lChoJ4wFbW9udGiUaCmIaCpdlGguKYGUfZRoMU5zYmF1YmgijA9EYXlPZk1vbnRoRmllbGSUk5QpgZR9lChoJ4wDZGF5lGgpiGgqXZRoLimBlH2UaDFOc2JhdWJoIowJV2Vla0ZpZWxklJOUKYGUfZQoaCeMBHdlZWuUaCmIaCpdlGguKYGUfZRoMU5zYmF1YmgijA5EYXlPZldlZWtGaWVsZJSTlCmBlH2UKGgnjAtkYXlfb2Zfd2Vla5RoKYloKl2UaCyMFldlZWtkYXlSYW5nZUV4cHJlc3Npb26Uk5QpgZR9lChoMU6MBWZpcnN0lEsBjARsYXN0lEsBdWJhdWJoJCmBlH2UKGgnjARob3VylGgpiWgqXZRoLIwPUmFuZ2VFeHByZXNzaW9ulJOUKYGUfZQoaDFOaFRLDWhVSw11YmF1YmgkKYGUfZQoaCeMBm1pbnV0ZZRoKYloKl2UaFspgZR9lChoMU5oVEsuaFVLLnViYXViaCQpgZR9lChoJ4wGc2Vjb25klGgpiGgqXZRoWymBlH2UKGgxTmhUSwBoVUsAdWJhdWJljAZqaXR0ZXKUTnVijAhleGVjdXRvcpSMB2RlZmF1bHSUjARhcmdzlCmMBmt3YXJnc5R9lGgnaAOMEm1pc2ZpcmVfZ3JhY2VfdGltZZRLAYwIY29hbGVzY2WUiIwNbWF4X2luc3RhbmNlc5RLAYwNbmV4dF9ydW5fdGltZZSMCGRhdGV0aW1llIwIZGF0ZXRpbWWUk5RDCgfnARENLgAAAACUaB2GlFKUdS4="}}, {"model": "django_apscheduler.djangojobexecution", "pk": 1, "fields": {"job": "my_job", "status": "Error!", "run_time": "2023-01-10T07:09:40Z", "duration": "0.32", "finished": "1673334580.32", "exception": "Cannot resolve keyword 'name' into field. Choices are: id, name_category, post, postcategory, subscribers", "traceback": "  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\apscheduler\\executors\\base.py\", line 125, in run_job\n    retval = job.func(*job.args, **job.kwargs)\n  File \"D:\\Python\\PycharmProject\\news_portal\\newspaper\\news\\management\\commands\\runapscheduler.py\", line 26, in my_job\n    categories = set(posts.values_list('category__name', flat=True))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1329, in values_list\n    clone = self._values(*_fields, **expressions)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1292, in _values\n    clone.query.set_values(fields)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2437, in set_values\n    self.add_fields(field_names, True)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2151, in add_fields\n    cols.append(join_info.transform_function(target, final_alias))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1835, in transform\n    raise last_field_exception\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1808, in setup_joins\n    path, final_field, targets, rest = self.names_to_path(\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1709, in names_to_path\n    raise FieldError(\n"}}, {"model": "django_apscheduler.djangojobexecution", "pk": 2, "fields": {"job": "my_job", "status": "Error!", "run_time": "2023-01-10T07:09:50Z", "duration": "0.33", "finished": "1673334590.33", "exception": "Cannot resolve keyword 'name' into field. Choices are: id, name_category, post, postcategory, subscribers", "traceback": "  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\apscheduler\\executors\\base.py\", line 125, in run_job\n    retval = job.func(*job.args, **job.kwargs)\n  File \"D:\\Python\\PycharmProject\\news_portal\\newspaper\\news\\management\\commands\\runapscheduler.py\", line 26, in my_job\n    categories = set(posts.values_list('category__name', flat=True))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1329, in values_list\n    clone = self._values(*_fields, **expressions)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1292, in _values\n    clone.query.set_values(fields)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2437, in set_values\n    self.add_fields(field_names, True)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2151, in add_fields\n    cols.append(join_info.transform_function(target, final_alias))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1835, in transform\n    raise last_field_exception\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1808, in setup_joins\n    path, final_field, targets, rest = self.names_to_path(\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1709, in names_to_path\n    raise FieldError(\n"}}, {"model": "django_apscheduler.djangojobexecution", "pk": 3, "fields": {"job": "my_job", "status": "Error!", "run_time": "2023-01-10T07:10:00Z", "duration": "0.30", "finished": "1673334600.30", "exception": "Cannot resolve keyword 'name' into field. Choices are: id, name_category, post, postcategory, subscribers", "traceback": "  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\apscheduler\\executors\\base.py\", line 125, in run_job\n    retval = job.func(*job.args, **job.kwargs)\n  File \"D:\\Python\\PycharmProject\\news_portal\\newspaper\\news\\management\\commands\\runapscheduler.py\", line 26, in my_job\n    categories = set(posts.values_list('category__name', flat=True))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1329, in values_list\n    clone = self._values(*_fields, **expressions)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1292, in _values\n    clone.query.set_values(fields)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2437, in set_values\n    self.add_fields(field_names, True)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2151, in add_fields\n    cols.append(join_info.transform_function(target, final_alias))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1835, in transform\n    raise last_field_exception\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1808, in setup_joins\n    path, final_field, targets, rest = self.names_to_path(\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1709, in names_to_path\n    raise FieldError(\n"}}, {"model": "django_apscheduler.djangojobexecution", "pk": 4, "fields": {"job": "my_job", "status": "Error!", "run_time": "2023-01-10T07:10:10Z", "duration": "0.20", "finished": "1673334610.20", "exception": "Cannot resolve keyword 'name' into field. Choices are: id, name_category, post, postcategory, subscribers", "traceback": "  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\apscheduler\\executors\\base.py\", line 125, in run_job\n    retval = job.func(*job.args, **job.kwargs)\n  File \"D:\\Python\\PycharmProject\\news_portal\\newspaper\\news\\management\\commands\\runapscheduler.py\", line 26, in my_job\n    categories = set(posts.values_list('category__name', flat=True))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1329, in values_list\n    clone = self._values(*_fields, **expressions)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1292, in _values\n    clone.query.set_values(fields)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2437, in set_values\n    self.add_fields(field_names, True)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2151, in add_fields\n    cols.append(join_info.transform_function(target, final_alias))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1835, in transform\n    raise last_field_exception\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1808, in setup_joins\n    path, final_field, targets, rest = self.names_to_path(\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1709, in names_to_path\n    raise FieldError(\n"}}, {"model": "django_apscheduler.djangojobexecution", "pk": 5, "fields": {"job": "my_job", "status": "Error!", "run_time": "2023-01-10T07:10:20Z", "duration": "0.21", "finished": "1673334620.21", "exception": "Cannot resolve keyword 'name' into field. Choices are: id, name_category, post, postcategory, subscribers", "traceback": "  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\apscheduler\\executors\\base.py\", line 125, in run_job\n    retval = job.func(*job.args, **job.kwargs)\n  File \"D:\\Python\\PycharmProject\\news_portal\\newspaper\\news\\management\\commands\\runapscheduler.py\", line 26, in my_job\n    categories = set(posts.values_list('category__name', flat=True))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1329, in values_list\n    clone = self._values(*_fields, **expressions)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1292, in _values\n    clone.query.set_values(fields)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2437, in set_values\n    self.add_fields(field_names, True)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2151, in add_fields\n    cols.append(join_info.transform_function(target, final_alias))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1835, in transform\n    raise last_field_exception\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1808, in setup_joins\n    path, final_field, targets, rest = self.names_to_path(\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1709, in names_to_path\n    raise FieldError(\n"}}, {"model": "django_apscheduler.djangojobexecution", "pk": 6, "fields": {"job": "my_job", "status": "Error!", "run_time": "2023-01-10T07:10:30Z", "duration": "0.20", "finished": "1673334630.20", "exception": "Cannot resolve keyword 'name' into field. Choices are: id, name_category, post, postcategory, subscribers", "traceback": "  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\apscheduler\\executors\\base.py\", line 125, in run_job\n    retval = job.func(*job.args, **job.kwargs)\n  File \"D:\\Python\\PycharmProject\\news_portal\\newspaper\\news\\management\\commands\\runapscheduler.py\", line 26, in my_job\n    categories = set(posts.values_list('category__name', flat=True))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1329, in values_list\n    clone = self._values(*_fields, **expressions)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1292, in _values\n    clone.query.set_values(fields)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2437, in set_values\n    self.add_fields(field_names, True)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2151, in add_fields\n    cols.append(join_info.transform_function(target, final_alias))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1835, in transform\n    raise last_field_exception\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1808, in setup_joins\n    path, final_field, targets, rest = self.names_to_path(\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1709, in names_to_path\n    raise FieldError(\n"}}, {"model": "django_apscheduler.djangojobexecution", "pk": 7, "fields": {"job": "my_job", "status": "Error!", "run_time": "2023-01-10T07:10:40Z", "duration": "0.19", "finished": "1673334640.19", "exception": "Cannot resolve keyword 'name' into field. Choices are: id, name_category, post, postcategory, subscribers", "traceback": "  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\apscheduler\\executors\\base.py\", line 125, in run_job\n    retval = job.func(*job.args, **job.kwargs)\n  File \"D:\\Python\\PycharmProject\\news_portal\\newspaper\\news\\management\\commands\\runapscheduler.py\", line 26, in my_job\n    categories = set(posts.values_list('category__name', flat=True))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1329, in values_list\n    clone = self._values(*_fields, **expressions)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1292, in _values\n    clone.query.set_values(fields)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2437, in set_values\n    self.add_fields(field_names, True)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2151, in add_fields\n    cols.append(join_info.transform_function(target, final_alias))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1835, in transform\n    raise last_field_exception\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1808, in setup_joins\n    path, final_field, targets, rest = self.names_to_path(\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1709, in names_to_path\n    raise FieldError(\n"}}, {"model": "django_apscheduler.djangojobexecution", "pk": 8, "fields": {"job": "my_job", "status": "Error!", "run_time": "2023-01-10T07:10:50Z", "duration": "0.20", "finished": "1673334650.20", "exception": "Cannot resolve keyword 'name' into field. Choices are: id, name_category, post, postcategory, subscribers", "traceback": "  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\apscheduler\\executors\\base.py\", line 125, in run_job\n    retval = job.func(*job.args, **job.kwargs)\n  File \"D:\\Python\\PycharmProject\\news_portal\\newspaper\\news\\management\\commands\\runapscheduler.py\", line 26, in my_job\n    categories = set(posts.values_list('category__name', flat=True))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1329, in values_list\n    clone = self._values(*_fields, **expressions)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1292, in _values\n    clone.query.set_values(fields)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2437, in set_values\n    self.add_fields(field_names, True)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2151, in add_fields\n    cols.append(join_info.transform_function(target, final_alias))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1835, in transform\n    raise last_field_exception\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1808, in setup_joins\n    path, final_field, targets, rest = self.names_to_path(\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1709, in names_to_path\n    raise FieldError(\n"}}, {"model": "django_apscheduler.djangojobexecution", "pk": 9, "fields": {"job": "my_job", "status": "Error!", "run_time": "2023-01-10T07:11:00Z", "duration": "0.19", "finished": "1673334660.19", "exception": "Cannot resolve keyword 'name' into field. Choices are: id, name_category, post, postcategory, subscribers", "traceback": "  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\apscheduler\\executors\\base.py\", line 125, in run_job\n    retval = job.func(*job.args, **job.kwargs)\n  File \"D:\\Python\\PycharmProject\\news_portal\\newspaper\\news\\management\\commands\\runapscheduler.py\", line 26, in my_job\n    categories = set(posts.values_list('category__name', flat=True))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1329, in values_list\n    clone = self._values(*_fields, **expressions)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1292, in _values\n    clone.query.set_values(fields)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2437, in set_values\n    self.add_fields(field_names, True)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2151, in add_fields\n    cols.append(join_info.transform_function(target, final_alias))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1835, in transform\n    raise last_field_exception\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1808, in setup_joins\n    path, final_field, targets, rest = self.names_to_path(\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1709, in names_to_path\n    raise FieldError(\n"}}, {"model": "django_apscheduler.djangojobexecution", "pk": 10, "fields": {"job": "my_job", "status": "Error!", "run_time": "2023-01-10T07:11:10Z", "duration": "0.20", "finished": "1673334670.20", "exception": "Cannot resolve keyword 'name' into field. Choices are: id, name_category, post, postcategory, subscribers", "traceback": "  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\apscheduler\\executors\\base.py\", line 125, in run_job\n    retval = job.func(*job.args, **job.kwargs)\n  File \"D:\\Python\\PycharmProject\\news_portal\\newspaper\\news\\management\\commands\\runapscheduler.py\", line 26, in my_job\n    categories = set(posts.values_list('category__name', flat=True))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1329, in values_list\n    clone = self._values(*_fields, **expressions)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1292, in _values\n    clone.query.set_values(fields)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2437, in set_values\n    self.add_fields(field_names, True)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2151, in add_fields\n    cols.append(join_info.transform_function(target, final_alias))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1835, in transform\n    raise last_field_exception\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1808, in setup_joins\n    path, final_field, targets, rest = self.names_to_path(\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1709, in names_to_path\n    raise FieldError(\n"}}, {"model": "django_apscheduler.djangojobexecution", "pk": 11, "fields": {"job": "my_job", "status": "Error!", "run_time": "2023-01-10T07:11:20Z", "duration": "0.19", "finished": "1673334680.19", "exception": "Cannot resolve keyword 'name' into field. Choices are: id, name_category, post, postcategory, subscribers", "traceback": "  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\apscheduler\\executors\\base.py\", line 125, in run_job\n    retval = job.func(*job.args, **job.kwargs)\n  File \"D:\\Python\\PycharmProject\\news_portal\\newspaper\\news\\management\\commands\\runapscheduler.py\", line 26, in my_job\n    categories = set(posts.values_list('category__name', flat=True))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1329, in values_list\n    clone = self._values(*_fields, **expressions)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1292, in _values\n    clone.query.set_values(fields)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2437, in set_values\n    self.add_fields(field_names, True)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2151, in add_fields\n    cols.append(join_info.transform_function(target, final_alias))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1835, in transform\n    raise last_field_exception\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1808, in setup_joins\n    path, final_field, targets, rest = self.names_to_path(\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1709, in names_to_path\n    raise FieldError(\n"}}, {"model": "django_apscheduler.djangojobexecution", "pk": 12, "fields": {"job": "my_job", "status": "Error!", "run_time": "2023-01-10T07:11:40Z", "duration": "0.03", "finished": "1673334700.03", "exception": "Cannot resolve keyword 'name' into field. Choices are: id, name_category, post, postcategory, subscribers", "traceback": "  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\apscheduler\\executors\\base.py\", line 125, in run_job\n    retval = job.func(*job.args, **job.kwargs)\n  File \"D:\\Python\\PycharmProject\\news_portal\\newspaper\\news\\management\\commands\\runapscheduler.py\", line 26, in my_job\n    categories = set(posts.values_list('category__name', flat=True))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1329, in values_list\n    clone = self._values(*_fields, **expressions)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1292, in _values\n    clone.query.set_values(fields)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2437, in set_values\n    self.add_fields(field_names, True)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2151, in add_fields\n    cols.append(join_info.transform_function(target, final_alias))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1835, in transform\n    raise last_field_exception\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1808, in setup_joins\n    path, final_field, targets, rest = self.names_to_path(\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1709, in names_to_path\n    raise FieldError(\n"}}, {"model": "django_apscheduler.djangojobexecution", "pk": 13, "fields": {"job": "my_job", "status": "Error!", "run_time": "2023-01-10T07:11:45Z", "duration": "0.20", "finished": "1673334705.20", "exception": "Cannot resolve keyword 'name' into field. Choices are: id, name_category, post, postcategory, subscribers", "traceback": "  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\apscheduler\\executors\\base.py\", line 125, in run_job\n    retval = job.func(*job.args, **job.kwargs)\n  File \"D:\\Python\\PycharmProject\\news_portal\\newspaper\\news\\management\\commands\\runapscheduler.py\", line 26, in my_job\n    categories = set(posts.values_list('category__name', flat=True))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1329, in values_list\n    clone = self._values(*_fields, **expressions)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1292, in _values\n    clone.query.set_values(fields)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2437, in set_values\n    self.add_fields(field_names, True)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2151, in add_fields\n    cols.append(join_info.transform_function(target, final_alias))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1835, in transform\n    raise last_field_exception\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1808, in setup_joins\n    path, final_field, targets, rest = self.names_to_path(\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1709, in names_to_path\n    raise FieldError(\n"}}, {"model": "django_apscheduler.djangojobexecution", "pk": 14, "fields": {"job": "my_job", "status": "Error!", "run_time": "2023-01-10T07:11:50Z", "duration": "0.19", "finished": "1673334710.19", "exception": "Cannot resolve keyword 'name' into field. Choices are: id, name_category, post, postcategory, subscribers", "traceback": "  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\apscheduler\\executors\\base.py\", line 125, in run_job\n    retval = job.func(*job.args, **job.kwargs)\n  File \"D:\\Python\\PycharmProject\\news_portal\\newspaper\\news\\management\\commands\\runapscheduler.py\", line 26, in my_job\n    categories = set(posts.values_list('category__name', flat=True))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1329, in values_list\n    clone = self._values(*_fields, **expressions)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1292, in _values\n    clone.query.set_values(fields)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2437, in set_values\n    self.add_fields(field_names, True)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2151, in add_fields\n    cols.append(join_info.transform_function(target, final_alias))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1835, in transform\n    raise last_field_exception\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1808, in setup_joins\n    path, final_field, targets, rest = self.names_to_path(\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1709, in names_to_path\n    raise FieldError(\n"}}, {"model": "django_apscheduler.djangojobexecution", "pk": 15, "fields": {"job": "my_job", "status": "Error!", "run_time": "2023-01-10T07:11:55Z", "duration": "0.20", "finished": "1673334715.20", "exception": "Cannot resolve keyword 'name' into field. Choices are: id, name_category, post, postcategory, subscribers", "traceback": "  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\apscheduler\\executors\\base.py\", line 125, in run_job\n    retval = job.func(*job.args, **job.kwargs)\n  File \"D:\\Python\\PycharmProject\\news_portal\\newspaper\\news\\management\\commands\\runapscheduler.py\", line 26, in my_job\n    categories = set(posts.values_list('category__name', flat=True))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1329, in values_list\n    clone = self._values(*_fields, **expressions)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1292, in _values\n    clone.query.set_values(fields)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2437, in set_values\n    self.add_fields(field_names, True)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2151, in add_fields\n    cols.append(join_info.transform_function(target, final_alias))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1835, in transform\n    raise last_field_exception\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1808, in setup_joins\n    path, final_field, targets, rest = self.names_to_path(\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1709, in names_to_path\n    raise FieldError(\n"}}, {"model": "django_apscheduler.djangojobexecution", "pk": 16, "fields": {"job": "my_job", "status": "Error!", "run_time": "2023-01-10T07:12:00Z", "duration": "0.20", "finished": "1673334720.20", "exception": "Cannot resolve keyword 'name' into field. Choices are: id, name_category, post, postcategory, subscribers", "traceback": "  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\apscheduler\\executors\\base.py\", line 125, in run_job\n    retval = job.func(*job.args, **job.kwargs)\n  File \"D:\\Python\\PycharmProject\\news_portal\\newspaper\\news\\management\\commands\\runapscheduler.py\", line 26, in my_job\n    categories = set(posts.values_list('category__name', flat=True))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1329, in values_list\n    clone = self._values(*_fields, **expressions)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1292, in _values\n    clone.query.set_values(fields)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2437, in set_values\n    self.add_fields(field_names, True)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2151, in add_fields\n    cols.append(join_info.transform_function(target, final_alias))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1835, in transform\n    raise last_field_exception\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1808, in setup_joins\n    path, final_field, targets, rest = self.names_to_path(\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1709, in names_to_path\n    raise FieldError(\n"}}, {"model": "django_apscheduler.djangojobexecution", "pk": 17, "fields": {"job": "my_job", "status": "Error!", "run_time": "2023-01-10T07:12:05Z", "duration": "0.20", "finished": "1673334725.20", "exception": "Cannot resolve keyword 'name' into field. Choices are: id, name_category, post, postcategory, subscribers", "traceback": "  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\apscheduler\\executors\\base.py\", line 125, in run_job\n    retval = job.func(*job.args, **job.kwargs)\n  File \"D:\\Python\\PycharmProject\\news_portal\\newspaper\\news\\management\\commands\\runapscheduler.py\", line 26, in my_job\n    categories = set(posts.values_list('category__name', flat=True))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1329, in values_list\n    clone = self._values(*_fields, **expressions)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1292, in _values\n    clone.query.set_values(fields)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2437, in set_values\n    self.add_fields(field_names, True)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2151, in add_fields\n    cols.append(join_info.transform_function(target, final_alias))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1835, in transform\n    raise last_field_exception\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1808, in setup_joins\n    path, final_field, targets, rest = self.names_to_path(\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1709, in names_to_path\n    raise FieldError(\n"}}, {"model": "django_apscheduler.djangojobexecution", "pk": 18, "fields": {"job": "my_job", "status": "Error!", "run_time": "2023-01-10T07:12:10Z", "duration": "0.21", "finished": "1673334730.21", "exception": "Cannot resolve keyword 'name' into field. Choices are: id, name_category, post, postcategory, subscribers", "traceback": "  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\apscheduler\\executors\\base.py\", line 125, in run_job\n    retval = job.func(*job.args, **job.kwargs)\n  File \"D:\\Python\\PycharmProject\\news_portal\\newspaper\\news\\management\\commands\\runapscheduler.py\", line 26, in my_job\n    categories = set(posts.values_list('category__name', flat=True))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1329, in values_list\n    clone = self._values(*_fields, **expressions)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1292, in _values\n    clone.query.set_values(fields)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2437, in set_values\n    self.add_fields(field_names, True)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2151, in add_fields\n    cols.append(join_info.transform_function(target, final_alias))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1835, in transform\n    raise last_field_exception\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1808, in setup_joins\n    path, final_field, targets, rest = self.names_to_path(\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1709, in names_to_path\n    raise FieldError(\n"}}, {"model": "django_apscheduler.djangojobexecution", "pk": 19, "fields": {"job": "my_job", "status": "Error!", "run_time": "2023-01-10T07:12:15Z", "duration": "0.22", "finished": "1673334735.22", "exception": "Cannot resolve keyword 'name' into field. Choices are: id, name_category, post, postcategory, subscribers", "traceback": "  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\apscheduler\\executors\\base.py\", line 125, in run_job\n    retval = job.func(*job.args, **job.kwargs)\n  File \"D:\\Python\\PycharmProject\\news_portal\\newspaper\\news\\management\\commands\\runapscheduler.py\", line 26, in my_job\n    categories = set(posts.values_list('category__name', flat=True))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1329, in values_list\n    clone = self._values(*_fields, **expressions)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1292, in _values\n    clone.query.set_values(fields)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2437, in set_values\n    self.add_fields(field_names, True)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2151, in add_fields\n    cols.append(join_info.transform_function(target, final_alias))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1835, in transform\n    raise last_field_exception\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1808, in setup_joins\n    path, final_field, targets, rest = self.names_to_path(\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1709, in names_to_path\n    raise FieldError(\n"}}, {"model": "django_apscheduler.djangojobexecution", "pk": 20, "fields": {"job": "my_job", "status": "Error!", "run_time": "2023-01-10T07:12:20Z", "duration": "0.20", "finished": "1673334740.20", "exception": "Cannot resolve keyword 'name' into field. Choices are: id, name_category, post, postcategory, subscribers", "traceback": "  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\apscheduler\\executors\\base.py\", line 125, in run_job\n    retval = job.func(*job.args, **job.kwargs)\n  File \"D:\\Python\\PycharmProject\\news_portal\\newspaper\\news\\management\\commands\\runapscheduler.py\", line 26, in my_job\n    categories = set(posts.values_list('category__name_category', flat=True))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1329, in values_list\n    clone = self._values(*_fields, **expressions)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1292, in _values\n    clone.query.set_values(fields)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2437, in set_values\n    self.add_fields(field_names, True)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2151, in add_fields\n    cols.append(join_info.transform_function(target, final_alias))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1835, in transform\n    raise last_field_exception\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1808, in setup_joins\n    path, final_field, targets, rest = self.names_to_path(\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1709, in names_to_path\n    raise FieldError(\n"}}, {"model": "django_apscheduler.djangojobexecution", "pk": 21, "fields": {"job": "my_job", "status": "Error!", "run_time": "2023-01-10T07:12:25Z", "duration": "0.20", "finished": "1673334745.20", "exception": "Cannot resolve keyword 'name' into field. Choices are: id, name_category, post, postcategory, subscribers", "traceback": "  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\apscheduler\\executors\\base.py\", line 125, in run_job\n    retval = job.func(*job.args, **job.kwargs)\n  File \"D:\\Python\\PycharmProject\\news_portal\\newspaper\\news\\management\\commands\\runapscheduler.py\", line 26, in my_job\n    categories = set(posts.values_list('category__name_category', flat=True))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1329, in values_list\n    clone = self._values(*_fields, **expressions)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1292, in _values\n    clone.query.set_values(fields)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2437, in set_values\n    self.add_fields(field_names, True)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2151, in add_fields\n    cols.append(join_info.transform_function(target, final_alias))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1835, in transform\n    raise last_field_exception\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1808, in setup_joins\n    path, final_field, targets, rest = self.names_to_path(\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1709, in names_to_path\n    raise FieldError(\n"}}, {"model": "django_apscheduler.djangojobexecution", "pk": 22, "fields": {"job": "my_job", "status": "Error!", "run_time": "2023-01-10T07:12:30Z", "duration": "0.18", "finished": "1673334750.18", "exception": "Cannot resolve keyword 'name' into field. Choices are: id, name_category, post, postcategory, subscribers", "traceback": "  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\apscheduler\\executors\\base.py\", line 125, in run_job\n    retval = job.func(*job.args, **job.kwargs)\n  File \"D:\\Python\\PycharmProject\\news_portal\\newspaper\\news\\management\\commands\\runapscheduler.py\", line 26, in my_job\n    categories = set(posts.values_list('category__name_category', flat=True))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1329, in values_list\n    clone = self._values(*_fields, **expressions)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1292, in _values\n    clone.query.set_values(fields)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2437, in set_values\n    self.add_fields(field_names, True)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2151, in add_fields\n    cols.append(join_info.transform_function(target, final_alias))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1835, in transform\n    raise last_field_exception\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1808, in setup_joins\n    path, final_field, targets, rest = self.names_to_path(\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1709, in names_to_path\n    raise FieldError(\n"}}, {"model": "django_apscheduler.djangojobexecution", "pk": 23, "fields": {"job": "my_job", "status": "Error!", "run_time": "2023-01-10T07:12:35Z", "duration": "0.21", "finished": "1673334755.21", "exception": "Cannot resolve keyword 'name' into field. Choices are: id, name_category, post, postcategory, subscribers", "traceback": "  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\apscheduler\\executors\\base.py\", line 125, in run_job\n    retval = job.func(*job.args, **job.kwargs)\n  File \"D:\\Python\\PycharmProject\\news_portal\\newspaper\\news\\management\\commands\\runapscheduler.py\", line 26, in my_job\n    categories = set(posts.values_list('category__name_category', flat=True))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1329, in values_list\n    clone = self._values(*_fields, **expressions)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1292, in _values\n    clone.query.set_values(fields)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2437, in set_values\n    self.add_fields(field_names, True)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2151, in add_fields\n    cols.append(join_info.transform_function(target, final_alias))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1835, in transform\n    raise last_field_exception\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1808, in setup_joins\n    path, final_field, targets, rest = self.names_to_path(\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1709, in names_to_path\n    raise FieldError(\n"}}, {"model": "django_apscheduler.djangojobexecution", "pk": 24, "fields": {"job": "my_job", "status": "Error!", "run_time": "2023-01-10T07:12:40Z", "duration": "0.21", "finished": "1673334760.21", "exception": "Cannot resolve keyword 'name' into field. Choices are: id, name_category, post, postcategory, subscribers", "traceback": "  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\apscheduler\\executors\\base.py\", line 125, in run_job\n    retval = job.func(*job.args, **job.kwargs)\n  File \"D:\\Python\\PycharmProject\\news_portal\\newspaper\\news\\management\\commands\\runapscheduler.py\", line 26, in my_job\n    categories = set(posts.values_list('category__name_category', flat=True))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1329, in values_list\n    clone = self._values(*_fields, **expressions)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1292, in _values\n    clone.query.set_values(fields)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2437, in set_values\n    self.add_fields(field_names, True)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2151, in add_fields\n    cols.append(join_info.transform_function(target, final_alias))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1835, in transform\n    raise last_field_exception\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1808, in setup_joins\n    path, final_field, targets, rest = self.names_to_path(\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1709, in names_to_path\n    raise FieldError(\n"}}, {"model": "django_apscheduler.djangojobexecution", "pk": 25, "fields": {"job": "my_job", "status": "Error!", "run_time": "2023-01-10T07:12:45Z", "duration": "0.20", "finished": "1673334765.20", "exception": "Cannot resolve keyword 'name' into field. Choices are: id, name_category, post, postcategory, subscribers", "traceback": "  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\apscheduler\\executors\\base.py\", line 125, in run_job\n    retval = job.func(*job.args, **job.kwargs)\n  File \"D:\\Python\\PycharmProject\\news_portal\\newspaper\\news\\management\\commands\\runapscheduler.py\", line 26, in my_job\n    categories = set(posts.values_list('category__name_category', flat=True))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1329, in values_list\n    clone = self._values(*_fields, **expressions)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1292, in _values\n    clone.query.set_values(fields)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2437, in set_values\n    self.add_fields(field_names, True)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2151, in add_fields\n    cols.append(join_info.transform_function(target, final_alias))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1835, in transform\n    raise last_field_exception\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1808, in setup_joins\n    path, final_field, targets, rest = self.names_to_path(\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1709, in names_to_path\n    raise FieldError(\n"}}, {"model": "django_apscheduler.djangojobexecution", "pk": 26, "fields": {"job": "my_job", "status": "Error!", "run_time": "2023-01-10T07:12:50Z", "duration": "0.19", "finished": "1673334770.19", "exception": "Cannot resolve keyword 'name' into field. Choices are: id, name_category, post, postcategory, subscribers", "traceback": "  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\apscheduler\\executors\\base.py\", line 125, in run_job\n    retval = job.func(*job.args, **job.kwargs)\n  File \"D:\\Python\\PycharmProject\\news_portal\\newspaper\\news\\management\\commands\\runapscheduler.py\", line 26, in my_job\n    categories = set(posts.values_list('category__name_category', flat=True))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1329, in values_list\n    clone = self._values(*_fields, **expressions)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1292, in _values\n    clone.query.set_values(fields)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2437, in set_values\n    self.add_fields(field_names, True)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2151, in add_fields\n    cols.append(join_info.transform_function(target, final_alias))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1835, in transform\n    raise last_field_exception\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1808, in setup_joins\n    path, final_field, targets, rest = self.names_to_path(\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1709, in names_to_path\n    raise FieldError(\n"}}, {"model": "django_apscheduler.djangojobexecution", "pk": 27, "fields": {"job": "my_job", "status": "Error!", "run_time": "2023-01-10T07:12:55Z", "duration": "0.19", "finished": "1673334775.19", "exception": "Cannot resolve keyword 'name' into field. Choices are: id, name_category, post, postcategory, subscribers", "traceback": "  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\apscheduler\\executors\\base.py\", line 125, in run_job\n    retval = job.func(*job.args, **job.kwargs)\n  File \"D:\\Python\\PycharmProject\\news_portal\\newspaper\\news\\management\\commands\\runapscheduler.py\", line 26, in my_job\n    categories = set(posts.values_list('category__name_category', flat=True))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1329, in values_list\n    clone = self._values(*_fields, **expressions)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1292, in _values\n    clone.query.set_values(fields)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2437, in set_values\n    self.add_fields(field_names, True)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2151, in add_fields\n    cols.append(join_info.transform_function(target, final_alias))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1835, in transform\n    raise last_field_exception\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1808, in setup_joins\n    path, final_field, targets, rest = self.names_to_path(\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1709, in names_to_path\n    raise FieldError(\n"}}, {"model": "django_apscheduler.djangojobexecution", "pk": 28, "fields": {"job": "my_job", "status": "Error!", "run_time": "2023-01-10T07:13:00Z", "duration": "0.19", "finished": "1673334780.19", "exception": "Cannot resolve keyword 'name' into field. Choices are: id, name_category, post, postcategory, subscribers", "traceback": "  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\apscheduler\\executors\\base.py\", line 125, in run_job\n    retval = job.func(*job.args, **job.kwargs)\n  File \"D:\\Python\\PycharmProject\\news_portal\\newspaper\\news\\management\\commands\\runapscheduler.py\", line 26, in my_job\n    categories = set(posts.values_list('category__name_category', flat=True))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1329, in values_list\n    clone = self._values(*_fields, **expressions)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1292, in _values\n    clone.query.set_values(fields)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2437, in set_values\n    self.add_fields(field_names, True)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2151, in add_fields\n    cols.append(join_info.transform_function(target, final_alias))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1835, in transform\n    raise last_field_exception\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1808, in setup_joins\n    path, final_field, targets, rest = self.names_to_path(\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1709, in names_to_path\n    raise FieldError(\n"}}, {"model": "django_apscheduler.djangojobexecution", "pk": 29, "fields": {"job": "my_job", "status": "Error!", "run_time": "2023-01-10T07:13:05Z", "duration": "0.20", "finished": "1673334785.20", "exception": "Cannot resolve keyword 'name' into field. Choices are: id, name_category, post, postcategory, subscribers", "traceback": "  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\apscheduler\\executors\\base.py\", line 125, in run_job\n    retval = job.func(*job.args, **job.kwargs)\n  File \"D:\\Python\\PycharmProject\\news_portal\\newspaper\\news\\management\\commands\\runapscheduler.py\", line 26, in my_job\n    categories = set(posts.values_list('category__name_category', flat=True))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1329, in values_list\n    clone = self._values(*_fields, **expressions)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1292, in _values\n    clone.query.set_values(fields)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2437, in set_values\n    self.add_fields(field_names, True)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2151, in add_fields\n    cols.append(join_info.transform_function(target, final_alias))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1835, in transform\n    raise last_field_exception\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1808, in setup_joins\n    path, final_field, targets, rest = self.names_to_path(\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1709, in names_to_path\n    raise FieldError(\n"}}, {"model": "django_apscheduler.djangojobexecution", "pk": 30, "fields": {"job": "my_job", "status": "Error!", "run_time": "2023-01-10T07:13:10Z", "duration": "0.29", "finished": "1673334790.29", "exception": "Cannot resolve keyword 'name' into field. Choices are: id, name_category, post, postcategory, subscribers", "traceback": "  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\apscheduler\\executors\\base.py\", line 125, in run_job\n    retval = job.func(*job.args, **job.kwargs)\n  File \"D:\\Python\\PycharmProject\\news_portal\\newspaper\\news\\management\\commands\\runapscheduler.py\", line 26, in my_job\n    categories = set(posts.values_list('category__name_category', flat=True))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1329, in values_list\n    clone = self._values(*_fields, **expressions)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1292, in _values\n    clone.query.set_values(fields)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2437, in set_values\n    self.add_fields(field_names, True)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2151, in add_fields\n    cols.append(join_info.transform_function(target, final_alias))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1835, in transform\n    raise last_field_exception\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1808, in setup_joins\n    path, final_field, targets, rest = self.names_to_path(\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1709, in names_to_path\n    raise FieldError(\n"}}, {"model": "django_apscheduler.djangojobexecution", "pk": 31, "fields": {"job": "my_job", "status": "Error!", "run_time": "2023-01-10T07:13:15Z", "duration": "0.20", "finished": "1673334795.20", "exception": "Cannot resolve keyword 'name' into field. Choices are: id, name_category, post, postcategory, subscribers", "traceback": "  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\apscheduler\\executors\\base.py\", line 125, in run_job\n    retval = job.func(*job.args, **job.kwargs)\n  File \"D:\\Python\\PycharmProject\\news_portal\\newspaper\\news\\management\\commands\\runapscheduler.py\", line 26, in my_job\n    categories = set(posts.values_list('category__name_category', flat=True))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1329, in values_list\n    clone = self._values(*_fields, **expressions)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1292, in _values\n    clone.query.set_values(fields)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2437, in set_values\n    self.add_fields(field_names, True)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2151, in add_fields\n    cols.append(join_info.transform_function(target, final_alias))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1835, in transform\n    raise last_field_exception\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1808, in setup_joins\n    path, final_field, targets, rest = self.names_to_path(\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1709, in names_to_path\n    raise FieldError(\n"}}, {"model": "django_apscheduler.djangojobexecution", "pk": 32, "fields": {"job": "my_job", "status": "Error!", "run_time": "2023-01-10T07:13:20Z", "duration": "0.21", "finished": "1673334800.21", "exception": "Cannot resolve keyword 'name' into field. Choices are: id, name_category, post, postcategory, subscribers", "traceback": "  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\apscheduler\\executors\\base.py\", line 125, in run_job\n    retval = job.func(*job.args, **job.kwargs)\n  File \"D:\\Python\\PycharmProject\\news_portal\\newspaper\\news\\management\\commands\\runapscheduler.py\", line 26, in my_job\n    categories = set(posts.values_list('category__name_category', flat=True))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1329, in values_list\n    clone = self._values(*_fields, **expressions)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1292, in _values\n    clone.query.set_values(fields)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2437, in set_values\n    self.add_fields(field_names, True)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2151, in add_fields\n    cols.append(join_info.transform_function(target, final_alias))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1835, in transform\n    raise last_field_exception\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1808, in setup_joins\n    path, final_field, targets, rest = self.names_to_path(\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1709, in names_to_path\n    raise FieldError(\n"}}, {"model": "django_apscheduler.djangojobexecution", "pk": 33, "fields": {"job": "my_job", "status": "Error!", "run_time": "2023-01-10T07:13:25Z", "duration": "0.20", "finished": "1673334805.20", "exception": "Cannot resolve keyword 'name' into field. Choices are: id, name_category, post, postcategory, subscribers", "traceback": "  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\apscheduler\\executors\\base.py\", line 125, in run_job\n    retval = job.func(*job.args, **job.kwargs)\n  File \"D:\\Python\\PycharmProject\\news_portal\\newspaper\\news\\management\\commands\\runapscheduler.py\", line 26, in my_job\n    categories = set(posts.values_list('category__name_category', flat=True))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1329, in values_list\n    clone = self._values(*_fields, **expressions)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1292, in _values\n    clone.query.set_values(fields)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2437, in set_values\n    self.add_fields(field_names, True)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2151, in add_fields\n    cols.append(join_info.transform_function(target, final_alias))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1835, in transform\n    raise last_field_exception\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1808, in setup_joins\n    path, final_field, targets, rest = self.names_to_path(\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1709, in names_to_path\n    raise FieldError(\n"}}, {"model": "django_apscheduler.djangojobexecution", "pk": 34, "fields": {"job": "my_job", "status": "Error!", "run_time": "2023-01-10T07:13:30Z", "duration": "0.21", "finished": "1673334810.21", "exception": "Cannot resolve keyword 'name' into field. Choices are: id, name_category, post, postcategory, subscribers", "traceback": "  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\apscheduler\\executors\\base.py\", line 125, in run_job\n    retval = job.func(*job.args, **job.kwargs)\n  File \"D:\\Python\\PycharmProject\\news_portal\\newspaper\\news\\management\\commands\\runapscheduler.py\", line 26, in my_job\n    categories = set(posts.values_list('category__name_category', flat=True))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1329, in values_list\n    clone = self._values(*_fields, **expressions)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1292, in _values\n    clone.query.set_values(fields)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2437, in set_values\n    self.add_fields(field_names, True)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2151, in add_fields\n    cols.append(join_info.transform_function(target, final_alias))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1835, in transform\n    raise last_field_exception\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1808, in setup_joins\n    path, final_field, targets, rest = self.names_to_path(\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1709, in names_to_path\n    raise FieldError(\n"}}, {"model": "django_apscheduler.djangojobexecution", "pk": 35, "fields": {"job": "my_job", "status": "Error!", "run_time": "2023-01-10T07:13:35Z", "duration": "0.21", "finished": "1673334815.21", "exception": "Cannot resolve keyword 'name' into field. Choices are: id, name_category, post, postcategory, subscribers", "traceback": "  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\apscheduler\\executors\\base.py\", line 125, in run_job\n    retval = job.func(*job.args, **job.kwargs)\n  File \"D:\\Python\\PycharmProject\\news_portal\\newspaper\\news\\management\\commands\\runapscheduler.py\", line 26, in my_job\n    categories = set(posts.values_list('category__name_category', flat=True))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1329, in values_list\n    clone = self._values(*_fields, **expressions)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1292, in _values\n    clone.query.set_values(fields)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2437, in set_values\n    self.add_fields(field_names, True)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2151, in add_fields\n    cols.append(join_info.transform_function(target, final_alias))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1835, in transform\n    raise last_field_exception\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1808, in setup_joins\n    path, final_field, targets, rest = self.names_to_path(\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1709, in names_to_path\n    raise FieldError(\n"}}, {"model": "django_apscheduler.djangojobexecution", "pk": 36, "fields": {"job": "my_job", "status": "Error!", "run_time": "2023-01-10T07:13:40Z", "duration": "0.21", "finished": "1673334820.21", "exception": "Cannot resolve keyword 'name' into field. Choices are: id, name_category, post, postcategory, subscribers", "traceback": "  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\apscheduler\\executors\\base.py\", line 125, in run_job\n    retval = job.func(*job.args, **job.kwargs)\n  File \"D:\\Python\\PycharmProject\\news_portal\\newspaper\\news\\management\\commands\\runapscheduler.py\", line 26, in my_job\n    categories = set(posts.values_list('category__name_category', flat=True))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1329, in values_list\n    clone = self._values(*_fields, **expressions)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1292, in _values\n    clone.query.set_values(fields)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2437, in set_values\n    self.add_fields(field_names, True)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2151, in add_fields\n    cols.append(join_info.transform_function(target, final_alias))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1835, in transform\n    raise last_field_exception\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1808, in setup_joins\n    path, final_field, targets, rest = self.names_to_path(\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1709, in names_to_path\n    raise FieldError(\n"}}, {"model": "django_apscheduler.djangojobexecution", "pk": 37, "fields": {"job": "my_job", "status": "Error!", "run_time": "2023-01-10T07:13:45Z", "duration": "0.20", "finished": "1673334825.20", "exception": "Cannot resolve keyword 'name' into field. Choices are: id, name_category, post, postcategory, subscribers", "traceback": "  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\apscheduler\\executors\\base.py\", line 125, in run_job\n    retval = job.func(*job.args, **job.kwargs)\n  File \"D:\\Python\\PycharmProject\\news_portal\\newspaper\\news\\management\\commands\\runapscheduler.py\", line 26, in my_job\n    categories = set(posts.values_list('category__name_category', flat=True))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1329, in values_list\n    clone = self._values(*_fields, **expressions)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1292, in _values\n    clone.query.set_values(fields)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2437, in set_values\n    self.add_fields(field_names, True)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2151, in add_fields\n    cols.append(join_info.transform_function(target, final_alias))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1835, in transform\n    raise last_field_exception\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1808, in setup_joins\n    path, final_field, targets, rest = self.names_to_path(\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1709, in names_to_path\n    raise FieldError(\n"}}, {"model": "django_apscheduler.djangojobexecution", "pk": 38, "fields": {"job": "my_job", "status": "Error!", "run_time": "2023-01-10T07:13:50Z", "duration": "0.22", "finished": "1673334830.22", "exception": "Cannot resolve keyword 'name' into field. Choices are: id, name_category, post, postcategory, subscribers", "traceback": "  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\apscheduler\\executors\\base.py\", line 125, in run_job\n    retval = job.func(*job.args, **job.kwargs)\n  File \"D:\\Python\\PycharmProject\\news_portal\\newspaper\\news\\management\\commands\\runapscheduler.py\", line 26, in my_job\n    categories = set(posts.values_list('category__name_category', flat=True))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1329, in values_list\n    clone = self._values(*_fields, **expressions)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1292, in _values\n    clone.query.set_values(fields)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2437, in set_values\n    self.add_fields(field_names, True)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2151, in add_fields\n    cols.append(join_info.transform_function(target, final_alias))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1835, in transform\n    raise last_field_exception\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1808, in setup_joins\n    path, final_field, targets, rest = self.names_to_path(\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1709, in names_to_path\n    raise FieldError(\n"}}, {"model": "django_apscheduler.djangojobexecution", "pk": 39, "fields": {"job": "my_job", "status": "Error!", "run_time": "2023-01-10T07:13:55Z", "duration": "0.22", "finished": "1673334835.22", "exception": "Cannot resolve keyword 'name' into field. Choices are: id, name_category, post, postcategory, subscribers", "traceback": "  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\apscheduler\\executors\\base.py\", line 125, in run_job\n    retval = job.func(*job.args, **job.kwargs)\n  File \"D:\\Python\\PycharmProject\\news_portal\\newspaper\\news\\management\\commands\\runapscheduler.py\", line 26, in my_job\n    categories = set(posts.values_list('category__name_category', flat=True))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1329, in values_list\n    clone = self._values(*_fields, **expressions)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1292, in _values\n    clone.query.set_values(fields)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2437, in set_values\n    self.add_fields(field_names, True)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2151, in add_fields\n    cols.append(join_info.transform_function(target, final_alias))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1835, in transform\n    raise last_field_exception\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1808, in setup_joins\n    path, final_field, targets, rest = self.names_to_path(\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1709, in names_to_path\n    raise FieldError(\n"}}, {"model": "django_apscheduler.djangojobexecution", "pk": 40, "fields": {"job": "my_job", "status": "Error!", "run_time": "2023-01-10T07:14:00Z", "duration": "0.18", "finished": "1673334840.18", "exception": "Cannot resolve keyword 'name' into field. Choices are: id, name_category, post, postcategory, subscribers", "traceback": "  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\apscheduler\\executors\\base.py\", line 125, in run_job\n    retval = job.func(*job.args, **job.kwargs)\n  File \"D:\\Python\\PycharmProject\\news_portal\\newspaper\\news\\management\\commands\\runapscheduler.py\", line 26, in my_job\n    categories = set(posts.values_list('category__name_category', flat=True))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1329, in values_list\n    clone = self._values(*_fields, **expressions)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1292, in _values\n    clone.query.set_values(fields)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2437, in set_values\n    self.add_fields(field_names, True)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2151, in add_fields\n    cols.append(join_info.transform_function(target, final_alias))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1835, in transform\n    raise last_field_exception\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1808, in setup_joins\n    path, final_field, targets, rest = self.names_to_path(\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1709, in names_to_path\n    raise FieldError(\n"}}, {"model": "django_apscheduler.djangojobexecution", "pk": 41, "fields": {"job": "my_job", "status": "Error!", "run_time": "2023-01-10T07:14:05Z", "duration": "0.20", "finished": "1673334845.20", "exception": "Cannot resolve keyword 'name' into field. Choices are: id, name_category, post, postcategory, subscribers", "traceback": "  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\apscheduler\\executors\\base.py\", line 125, in run_job\n    retval = job.func(*job.args, **job.kwargs)\n  File \"D:\\Python\\PycharmProject\\news_portal\\newspaper\\news\\management\\commands\\runapscheduler.py\", line 26, in my_job\n    categories = set(posts.values_list('category__name_category', flat=True))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1329, in values_list\n    clone = self._values(*_fields, **expressions)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1292, in _values\n    clone.query.set_values(fields)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2437, in set_values\n    self.add_fields(field_names, True)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2151, in add_fields\n    cols.append(join_info.transform_function(target, final_alias))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1835, in transform\n    raise last_field_exception\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1808, in setup_joins\n    path, final_field, targets, rest = self.names_to_path(\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1709, in names_to_path\n    raise FieldError(\n"}}, {"model": "django_apscheduler.djangojobexecution", "pk": 42, "fields": {"job": "my_job", "status": "Error!", "run_time": "2023-01-10T07:14:10Z", "duration": "0.20", "finished": "1673334850.20", "exception": "Cannot resolve keyword 'name' into field. Choices are: id, name_category, post, postcategory, subscribers", "traceback": "  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\apscheduler\\executors\\base.py\", line 125, in run_job\n    retval = job.func(*job.args, **job.kwargs)\n  File \"D:\\Python\\PycharmProject\\news_portal\\newspaper\\news\\management\\commands\\runapscheduler.py\", line 26, in my_job\n    categories = set(posts.values_list('category__name_category', flat=True))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1329, in values_list\n    clone = self._values(*_fields, **expressions)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1292, in _values\n    clone.query.set_values(fields)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2437, in set_values\n    self.add_fields(field_names, True)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2151, in add_fields\n    cols.append(join_info.transform_function(target, final_alias))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1835, in transform\n    raise last_field_exception\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1808, in setup_joins\n    path, final_field, targets, rest = self.names_to_path(\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1709, in names_to_path\n    raise FieldError(\n"}}, {"model": "django_apscheduler.djangojobexecution", "pk": 43, "fields": {"job": "my_job", "status": "Error!", "run_time": "2023-01-10T07:14:15Z", "duration": "0.19", "finished": "1673334855.19", "exception": "Cannot resolve keyword 'name' into field. Choices are: id, name_category, post, postcategory, subscribers", "traceback": "  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\apscheduler\\executors\\base.py\", line 125, in run_job\n    retval = job.func(*job.args, **job.kwargs)\n  File \"D:\\Python\\PycharmProject\\news_portal\\newspaper\\news\\management\\commands\\runapscheduler.py\", line 26, in my_job\n    categories = set(posts.values_list('category__name_category', flat=True))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1329, in values_list\n    clone = self._values(*_fields, **expressions)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1292, in _values\n    clone.query.set_values(fields)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2437, in set_values\n    self.add_fields(field_names, True)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2151, in add_fields\n    cols.append(join_info.transform_function(target, final_alias))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1835, in transform\n    raise last_field_exception\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1808, in setup_joins\n    path, final_field, targets, rest = self.names_to_path(\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1709, in names_to_path\n    raise FieldError(\n"}}, {"model": "django_apscheduler.djangojobexecution", "pk": 44, "fields": {"job": "my_job", "status": "Error!", "run_time": "2023-01-10T07:14:20Z", "duration": "0.32", "finished": "1673334860.32", "exception": "Cannot resolve keyword 'name' into field. Choices are: id, name_category, post, postcategory, subscribers", "traceback": "  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\apscheduler\\executors\\base.py\", line 125, in run_job\n    retval = job.func(*job.args, **job.kwargs)\n  File \"D:\\Python\\PycharmProject\\news_portal\\newspaper\\news\\management\\commands\\runapscheduler.py\", line 26, in my_job\n    categories = set(posts.values_list('category__name_category', flat=True))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1329, in values_list\n    clone = self._values(*_fields, **expressions)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1292, in _values\n    clone.query.set_values(fields)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2437, in set_values\n    self.add_fields(field_names, True)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2151, in add_fields\n    cols.append(join_info.transform_function(target, final_alias))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1835, in transform\n    raise last_field_exception\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1808, in setup_joins\n    path, final_field, targets, rest = self.names_to_path(\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1709, in names_to_path\n    raise FieldError(\n"}}, {"model": "django_apscheduler.djangojobexecution", "pk": 45, "fields": {"job": "my_job", "status": "Error!", "run_time": "2023-01-10T07:14:25Z", "duration": "0.19", "finished": "1673334865.19", "exception": "Cannot resolve keyword 'name' into field. Choices are: id, name_category, post, postcategory, subscribers", "traceback": "  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\apscheduler\\executors\\base.py\", line 125, in run_job\n    retval = job.func(*job.args, **job.kwargs)\n  File \"D:\\Python\\PycharmProject\\news_portal\\newspaper\\news\\management\\commands\\runapscheduler.py\", line 26, in my_job\n    categories = set(posts.values_list('category__name', flat=True))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1329, in values_list\n    clone = self._values(*_fields, **expressions)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1292, in _values\n    clone.query.set_values(fields)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2437, in set_values\n    self.add_fields(field_names, True)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2151, in add_fields\n    cols.append(join_info.transform_function(target, final_alias))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1835, in transform\n    raise last_field_exception\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1808, in setup_joins\n    path, final_field, targets, rest = self.names_to_path(\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1709, in names_to_path\n    raise FieldError(\n"}}, {"model": "django_apscheduler.djangojobexecution", "pk": 46, "fields": {"job": "my_job", "status": "Error!", "run_time": "2023-01-10T07:14:30Z", "duration": "0.29", "finished": "1673334870.29", "exception": "Cannot resolve keyword 'name' into field. Choices are: id, name_category, post, postcategory, subscribers", "traceback": "  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\apscheduler\\executors\\base.py\", line 125, in run_job\n    retval = job.func(*job.args, **job.kwargs)\n  File \"D:\\Python\\PycharmProject\\news_portal\\newspaper\\news\\management\\commands\\runapscheduler.py\", line 26, in my_job\n    categories = set(posts.values_list('category__name', flat=True))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1329, in values_list\n    clone = self._values(*_fields, **expressions)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1292, in _values\n    clone.query.set_values(fields)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2437, in set_values\n    self.add_fields(field_names, True)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2151, in add_fields\n    cols.append(join_info.transform_function(target, final_alias))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1835, in transform\n    raise last_field_exception\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1808, in setup_joins\n    path, final_field, targets, rest = self.names_to_path(\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1709, in names_to_path\n    raise FieldError(\n"}}, {"model": "django_apscheduler.djangojobexecution", "pk": 47, "fields": {"job": "my_job", "status": "Error!", "run_time": "2023-01-10T07:14:35Z", "duration": "0.27", "finished": "1673334875.27", "exception": "Cannot resolve keyword 'name' into field. Choices are: id, name_category, post, postcategory, subscribers", "traceback": "  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\apscheduler\\executors\\base.py\", line 125, in run_job\n    retval = job.func(*job.args, **job.kwargs)\n  File \"D:\\Python\\PycharmProject\\news_portal\\newspaper\\news\\management\\commands\\runapscheduler.py\", line 26, in my_job\n    categories = set(posts.values_list('category__name', flat=True))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1329, in values_list\n    clone = self._values(*_fields, **expressions)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1292, in _values\n    clone.query.set_values(fields)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2437, in set_values\n    self.add_fields(field_names, True)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2151, in add_fields\n    cols.append(join_info.transform_function(target, final_alias))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1835, in transform\n    raise last_field_exception\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1808, in setup_joins\n    path, final_field, targets, rest = self.names_to_path(\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1709, in names_to_path\n    raise FieldError(\n"}}, {"model": "django_apscheduler.djangojobexecution", "pk": 48, "fields": {"job": "my_job", "status": "Error!", "run_time": "2023-01-10T07:14:40Z", "duration": "0.29", "finished": "1673334880.29", "exception": "Cannot resolve keyword 'name' into field. Choices are: id, name_category, post, postcategory, subscribers", "traceback": "  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\apscheduler\\executors\\base.py\", line 125, in run_job\n    retval = job.func(*job.args, **job.kwargs)\n  File \"D:\\Python\\PycharmProject\\news_portal\\newspaper\\news\\management\\commands\\runapscheduler.py\", line 26, in my_job\n    categories = set(posts.values_list('category__name', flat=True))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1329, in values_list\n    clone = self._values(*_fields, **expressions)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1292, in _values\n    clone.query.set_values(fields)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2437, in set_values\n    self.add_fields(field_names, True)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2151, in add_fields\n    cols.append(join_info.transform_function(target, final_alias))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1835, in transform\n    raise last_field_exception\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1808, in setup_joins\n    path, final_field, targets, rest = self.names_to_path(\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1709, in names_to_path\n    raise FieldError(\n"}}, {"model": "django_apscheduler.djangojobexecution", "pk": 49, "fields": {"job": "my_job", "status": "Error!", "run_time": "2023-01-10T07:14:45Z", "duration": "0.27", "finished": "1673334885.27", "exception": "Cannot resolve keyword 'name' into field. Choices are: id, name_category, post, postcategory, subscribers", "traceback": "  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\apscheduler\\executors\\base.py\", line 125, in run_job\n    retval = job.func(*job.args, **job.kwargs)\n  File \"D:\\Python\\PycharmProject\\news_portal\\newspaper\\news\\management\\commands\\runapscheduler.py\", line 26, in my_job\n    categories = set(posts.values_list('category__name', flat=True))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1329, in values_list\n    clone = self._values(*_fields, **expressions)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1292, in _values\n    clone.query.set_values(fields)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2437, in set_values\n    self.add_fields(field_names, True)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2151, in add_fields\n    cols.append(join_info.transform_function(target, final_alias))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1835, in transform\n    raise last_field_exception\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1808, in setup_joins\n    path, final_field, targets, rest = self.names_to_path(\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1709, in names_to_path\n    raise FieldError(\n"}}, {"model": "django_apscheduler.djangojobexecution", "pk": 50, "fields": {"job": "my_job", "status": "Error!", "run_time": "2023-01-10T07:14:50Z", "duration": "0.33", "finished": "1673334890.33", "exception": "Cannot resolve keyword 'name' into field. Choices are: id, name_category, post, postcategory, subscribers", "traceback": "  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\apscheduler\\executors\\base.py\", line 125, in run_job\n    retval = job.func(*job.args, **job.kwargs)\n  File \"D:\\Python\\PycharmProject\\news_portal\\newspaper\\news\\management\\commands\\runapscheduler.py\", line 26, in my_job\n    categories = set(posts.values_list('category__name', flat=True))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1329, in values_list\n    clone = self._values(*_fields, **expressions)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1292, in _values\n    clone.query.set_values(fields)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2437, in set_values\n    self.add_fields(field_names, True)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2151, in add_fields\n    cols.append(join_info.transform_function(target, final_alias))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1835, in transform\n    raise last_field_exception\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1808, in setup_joins\n    path, final_field, targets, rest = self.names_to_path(\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1709, in names_to_path\n    raise FieldError(\n"}}, {"model": "django_apscheduler.djangojobexecution", "pk": 51, "fields": {"job": "my_job", "status": "Error!", "run_time": "2023-01-10T07:14:55Z", "duration": "0.21", "finished": "1673334895.21", "exception": "Cannot resolve keyword 'name' into field. Choices are: id, name_category, post, postcategory, subscribers", "traceback": "  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\apscheduler\\executors\\base.py\", line 125, in run_job\n    retval = job.func(*job.args, **job.kwargs)\n  File \"D:\\Python\\PycharmProject\\news_portal\\newspaper\\news\\management\\commands\\runapscheduler.py\", line 26, in my_job\n    categories = set(posts.values_list('category__name', flat=True))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1329, in values_list\n    clone = self._values(*_fields, **expressions)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1292, in _values\n    clone.query.set_values(fields)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2437, in set_values\n    self.add_fields(field_names, True)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2151, in add_fields\n    cols.append(join_info.transform_function(target, final_alias))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1835, in transform\n    raise last_field_exception\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1808, in setup_joins\n    path, final_field, targets, rest = self.names_to_path(\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1709, in names_to_path\n    raise FieldError(\n"}}, {"model": "django_apscheduler.djangojobexecution", "pk": 52, "fields": {"job": "my_job", "status": "Error!", "run_time": "2023-01-10T07:15:00Z", "duration": "0.18", "finished": "1673334900.18", "exception": "Cannot resolve keyword 'name' into field. Choices are: id, name_category, post, postcategory, subscribers", "traceback": "  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\apscheduler\\executors\\base.py\", line 125, in run_job\n    retval = job.func(*job.args, **job.kwargs)\n  File \"D:\\Python\\PycharmProject\\news_portal\\newspaper\\news\\management\\commands\\runapscheduler.py\", line 26, in my_job\n    categories = set(posts.values_list('category__name', flat=True))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1329, in values_list\n    clone = self._values(*_fields, **expressions)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1292, in _values\n    clone.query.set_values(fields)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2437, in set_values\n    self.add_fields(field_names, True)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2151, in add_fields\n    cols.append(join_info.transform_function(target, final_alias))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1835, in transform\n    raise last_field_exception\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1808, in setup_joins\n    path, final_field, targets, rest = self.names_to_path(\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1709, in names_to_path\n    raise FieldError(\n"}}, {"model": "django_apscheduler.djangojobexecution", "pk": 53, "fields": {"job": "my_job", "status": "Error!", "run_time": "2023-01-10T07:15:05Z", "duration": "0.18", "finished": "1673334905.18", "exception": "Cannot resolve keyword 'name' into field. Choices are: id, name_category, post, postcategory, subscribers", "traceback": "  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\apscheduler\\executors\\base.py\", line 125, in run_job\n    retval = job.func(*job.args, **job.kwargs)\n  File \"D:\\Python\\PycharmProject\\news_portal\\newspaper\\news\\management\\commands\\runapscheduler.py\", line 26, in my_job\n    categories = set(posts.values_list('category__name_category', flat=True))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1329, in values_list\n    clone = self._values(*_fields, **expressions)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\query.py\", line 1292, in _values\n    clone.query.set_values(fields)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2437, in set_values\n    self.add_fields(field_names, True)\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 2151, in add_fields\n    cols.append(join_info.transform_function(target, final_alias))\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1835, in transform\n    raise last_field_exception\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1808, in setup_joins\n    path, final_field, targets, rest = self.names_to_path(\n  File \"D:\\Python\\PycharmProject\\news_portal\\venv\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1709, in names_to_path\n    raise FieldError(\n"}}, {"model": "django_apscheduler.djangojobexecution", "pk": 54, "fields": {"job": "my_job", "status": "Executed", "run_time": "2023-01-10T07:15:15Z", "duration": "0.96", "finished": "1673334915.96", "exception": null, "traceback": null}}, {"model": "django_apscheduler.djangojobexecution", "pk": 55, "fields": {"job": "my_job", "status": "Executed", "run_time": "2023-01-10T07:15:20Z", "duration": "0.92", "finished": "1673334920.92", "exception": null, "traceback": null}}, {"model": "django_apscheduler.djangojobexecution", "pk": 56, "fields": {"job": "my_job", "status": "Executed", "run_time": "2023-01-10T07:15:25Z", "duration": "1.12", "finished": "1673334926.12", "exception": null, "traceback": null}}, {"model": "django_apscheduler.djangojobexecution", "pk": 57, "fields": {"job": "my_job", "status": "Executed", "run_time": "2023-01-10T07:15:30Z", "duration": "1.02", "finished": "1673334931.02", "exception": null, "traceback": null}}, {"model": "django_apscheduler.djangojobexecution", "pk": 58, "fields": {"job": "my_job", "status": "Executed", "run_time": "2023-01-10T07:15:35Z", "duration": "1.16", "finished": "1673334936.16", "exception": null, "traceback": null}}, {"model": "django_apscheduler.djangojobexecution", "pk": 59, "fields": {"job": "my_job", "status": "Executed", "run_time": "2023-01-10T07:15:40Z", "duration": "1.18", "finished": "1673334941.18", "exception": null, "traceback": null}}, {"model": "django_apscheduler.djangojobexecution", "pk": 60, "fields": {"job": "my_job", "status": "Executed", "run_time": "2023-01-10T07:19:45Z", "duration": "1.25", "finished": "1673335186.25", "exception": null, "traceback": null}}, {"model": "django_apscheduler.djangojobexecution", "pk": 61, "fields": {"job": "my_job", "status": "Executed", "run_time": "2023-01-10T07:19:50Z", "duration": "1.39", "finished": "1673335191.39", "exception": null, "traceback": null}}, {"model": "django_apscheduler.djangojobexecution", "pk": 62, "fields": {"job": "my_job", "status": "Executed", "run_time": "2023-01-10T07:46:00Z", "duration": "1.25", "finished": "1673336761.25", "exception": null, "traceback": null}}]